-- The Starry Palace · curated vocabulary expansion. Repeat-safe and additive.
-- Preserve all existing community tags, counts, canonicals and usage links.
-- Curated standalone descriptors rather than synthetic pairwise keyword spam.
WITH catalogue(category,name) AS (
 VALUES
 ('genre','Cli-fi'),
 ('genre','New Weird'),
 ('genre','Speculative Memoir'),
 ('genre','Island Gothic'),
 ('genre','Caribbean Noir'),
 ('genre','Afro-Gothic'),
 ('genre','Mythic Detective Fiction'),
 ('genre','Folklore Retelling'),
 ('genre','Climate Gothic'),
 ('genre','Coastal Horror'),
 ('genre','Magical Domestic Fiction'),
 ('genre','Hopeful Dystopia'),
 ('genre','Diaspora Romance'),
 ('genre','Sailor''s Tale'),
 ('genre','Oral History Fiction'),
 ('genre','Ballad Novel'),
 ('genre','Epistolary Horror'),
 ('genre','Historical Family Mystery'),
 ('genre','Postcolonial Fantasy'),
 ('genre','Maritime Fantasy'),
 ('genre','Literary Suspense'),
 ('genre','Biopunk Mystery'),
 ('genre','Solarpunk Romance'),
 ('genre','Campus Gothic'),
 ('genre','Decolonial Science Fiction'),
 ('genre','Mythological Space Opera'),
 ('genre','Quiet Fantasy'),
 ('genre','Cottagecore Fantasy'),
 ('genre','Folkloric Mystery'),
 ('genre','Spiritual Journey Fiction'),
 ('genre','Ghostly Historical Romance'),
 ('genre','Regional Noir'),
 ('genre','Speculative Legal Drama'),
 ('genre','Liminal Fiction'),
 ('genre','Archive Fiction'),
 ('genre','Dark Folklore'),
 ('genre','Intergenerational Drama'),
 ('genre','Dream-Logic Horror'),
 ('genre','Political Allegory'),
 ('genre','Diaspora Speculative Fiction'),
 ('trope','Letters Never Sent'),
 ('trope','Unwanted Coronation'),
 ('trope','Unreliable Prophecy'),
 ('trope','Secret Pen Pal'),
 ('trope','Lost at Sea'),
 ('trope','Last of Their Line'),
 ('trope','Hidden Twin'),
 ('trope','False Identity at Court'),
 ('trope','Enemy''s Last Wish'),
 ('trope','Reunion at the Funeral'),
 ('trope','Inherited Curse'),
 ('trope','Unspoken Vow'),
 ('trope','Accidental Time Loop'),
 ('trope','Witness in Hiding'),
 ('trope','The Villain''s Apology'),
 ('trope','History Repeats Differently'),
 ('trope','Sacrifice Refused'),
 ('trope','Royal Impostor'),
 ('trope','Secret Heir Revealed'),
 ('trope','Family Archive Found'),
 ('trope','An Inheritance of Debts'),
 ('trope','Second Wedding'),
 ('trope','The Missing Page'),
 ('trope','Strangers on a Ferry'),
 ('trope','Last Train Home'),
 ('trope','Ancient Oath Broken'),
 ('trope','False Confession'),
 ('trope','Unlikely Guardian'),
 ('trope','Truth Hidden in Song'),
 ('trope','A Reunion After War'),
 ('trope','A Secret in Plain Sight'),
 ('trope','Mentor Goes Missing'),
 ('trope','Small Town Election'),
 ('trope','A Promised Return'),
 ('trope','The Only Witness'),
 ('trope','Two Truths One Lie'),
 ('trope','Past Lives Reunited'),
 ('trope','A Hero Who Quits'),
 ('trope','Divine Contract Loophole'),
 ('trope','Reckless Act of Kindness'),
 ('mood','Elegiac'),
 ('mood','Brooding'),
 ('mood','Hopeful Melancholy'),
 ('mood','Bittersweet Triumph'),
 ('mood','Quietly Defiant'),
 ('mood','Ceremonial'),
 ('mood','Moon-drenched'),
 ('mood','Ritualistic'),
 ('mood','Lyrical Grief'),
 ('mood','Hauntingly Gentle'),
 ('mood','Warmly Irreverent'),
 ('mood','Stormy Romantic'),
 ('mood','Somber Celebration'),
 ('mood','Unsettlingly Tender'),
 ('mood','Dramatic Restraint'),
 ('mood','Dreamy Suspense'),
 ('mood','Softly Ominous'),
 ('mood','Reverent'),
 ('mood','Restless'),
 ('mood','Sunlit Nostalgia'),
 ('mood','Wistfully Heroic'),
 ('mood','Feverish Wonder'),
 ('mood','Contemplative Wonder'),
 ('mood','Joy After Loss'),
 ('mood','Mischievous'),
 ('mood','Tense and Witty'),
 ('mood','Tenderly Awkward'),
 ('mood','Bitterly Funny'),
 ('mood','Oceanic Longing'),
 ('mood','Awe After Fear'),
 ('mood','Quiet Hope'),
 ('mood','Ethereal Sadness'),
 ('mood','Lonely Yet Hopeful'),
 ('mood','Lush and Foreboding'),
 ('mood','Giddy with Secrets'),
 ('setting','Caribbean Ferry Crossing'),
 ('setting','Tobago Fishing Village'),
 ('setting','Island Market at Dawn'),
 ('setting','Rainforest Shrine'),
 ('setting','Haunted Botanical Garden'),
 ('setting','Underwater Observatory'),
 ('setting','Lunar Greenhouse'),
 ('setting','Desert Caravanserai'),
 ('setting','Mountain Monastery'),
 ('setting','Old Railway Post Office'),
 ('setting','Coastal Archives'),
 ('setting','Storm-Bound Guest House'),
 ('setting','Abandoned Observatory'),
 ('setting','Moonlit Carnival'),
 ('setting','Floating Library'),
 ('setting','Seaside Convalescent Home'),
 ('setting','Overgrown Imperial Courtyard'),
 ('setting','Courtroom at Midnight'),
 ('setting','Family Home Before Sale'),
 ('setting','Village Cinema'),
 ('setting','Midnight Bus Depot'),
 ('setting','Salt Flats at Sunrise'),
 ('setting','Hidden Valley School'),
 ('setting','Small Island Parliament'),
 ('setting','Old Lighthouse Keepers'' Cottage'),
 ('setting','River Delta Settlement'),
 ('setting','Ship''s Medical Bay'),
 ('setting','Submerged Palace'),
 ('setting','Rooftop Tea Garden'),
 ('setting','Winter Orchard'),
 ('setting','Night Train Dining Car'),
 ('setting','Space Station Chapel'),
 ('setting','Royal Archives Basement'),
 ('setting','Crumbling Family Estate'),
 ('setting','Caravan at the Border'),
 ('setting','Mountain Tea House'),
 ('setting','Festival Market Street'),
 ('setting','Sea Cave Sanctuary'),
 ('setting','Antique Book Restoration Studio'),
 ('setting','Underground Theatre'),
 ('theme','Inheritance of Silence'),
 ('theme','The Ethics of Discovery'),
 ('theme','Collective Memory'),
 ('theme','The Burden of Tradition'),
 ('theme','Truth Versus Loyalty'),
 ('theme','Second Chances'),
 ('theme','Ordinary Heroism'),
 ('theme','Inherited Grief'),
 ('theme','Chosen Duty'),
 ('theme','Family Expectations'),
 ('theme','Ethics of Care'),
 ('theme','The Cost of Ambition'),
 ('theme','Memory and Oblivion'),
 ('theme','Power Without Glory'),
 ('theme','The Weight of a Name'),
 ('theme','Community Accountability'),
 ('theme','Mourning and Renewal'),
 ('theme','Courage to Leave'),
 ('theme','Home After Exile'),
 ('theme','Duty Versus Desire'),
 ('theme','The Price of Mercy'),
 ('theme','Forgiveness Without Forgetting'),
 ('theme','Abolishing an Unjust Law'),
 ('theme','Intergenerational Healing'),
 ('theme','Faith and Doubt'),
 ('theme','Hope After Disaster'),
 ('theme','Consent and Power'),
 ('theme','What Makes a Home'),
 ('theme','The Value of Art'),
 ('theme','Resisting Erasure'),
 ('theme','Public Reputation Versus Private Truth'),
 ('theme','A Community''s Future'),
 ('theme','Belonging Across Borders'),
 ('theme','Beauty and Impermanence'),
 ('theme','Loyalty Under Pressure'),
 ('theme','Truth in Folklore'),
 ('theme','The Right to Rest'),
 ('theme','Unexpected Solidarity'),
 ('theme','Silence as Resistance'),
 ('theme','Rediscovering Joy'),
 ('relationship','Estranged Grandparents and Grandchildren'),
 ('relationship','Three Generations of Women'),
 ('relationship','Elder and Apprentice'),
 ('relationship','Neighbours to Family'),
 ('relationship','Rival Historians'),
 ('relationship','Siblings Across Continents'),
 ('relationship','Co-Parents After Separation'),
 ('relationship','Friends After Betrayal'),
 ('relationship','Teacher and Returning Student'),
 ('relationship','Former Bandmates'),
 ('relationship','Second Chance Friendship'),
 ('relationship','Found Siblings'),
 ('relationship','Mentor and Former Rival'),
 ('relationship','Widowed Parent and Adult Child'),
 ('relationship','Royal Guardian and Heir'),
 ('relationship','Two Mothers Raising a Child'),
 ('relationship','Aunt and Niece'),
 ('relationship','Adopted Siblings'),
 ('relationship','Two Unreliable Narrators'),
 ('relationship','Married Rivals'),
 ('relationship','Queer Found Family'),
 ('relationship','Former Friends to Co-Writers'),
 ('relationship','Exiles Reunited'),
 ('relationship','Shared Custody of a Secret'),
 ('relationship','Long-Distance Best Friends'),
 ('relationship','Caretaker and Patient'),
 ('relationship','Lovers Across Eras'),
 ('relationship','Mentor and Apprentice Rivals'),
 ('relationship','Sibling Reconciliation'),
 ('relationship','Unexpected Co-Guardians'),
 ('relationship','Chosen Grandparents'),
 ('relationship','Arranged Marriage of Convenience'),
 ('relationship','Divorced Couple on a Journey'),
 ('relationship','Workplace Friends'),
 ('relationship','Strangers Becoming Kin'),
 ('character','Reluctant Archivist'),
 ('character','Village Midwife'),
 ('character','Night-Shift Librarian'),
 ('character','Community Radio Host'),
 ('character','Court Translator'),
 ('character','Travelling Storyteller'),
 ('character','Former Royal Guard'),
 ('character','Widowed Cartographer'),
 ('character','Folklore Researcher'),
 ('character','Marine Archaeologist'),
 ('character','Island Botanist'),
 ('character','Retired Spy'),
 ('character','Unwilling Prophet'),
 ('character','Royal Clerk'),
 ('character','Palace Musician'),
 ('character','Museum Conservator'),
 ('character','Amateur Detective'),
 ('character','Haunted Poet'),
 ('character','Kite Maker'),
 ('character','Disgraced Heir'),
 ('character','Disappearing Magician'),
 ('character','Aging Explorer'),
 ('character','Village Elder'),
 ('character','Skeptical Priest'),
 ('character','Community Organizer'),
 ('character','Investigative Journalist'),
 ('character','Time-Lost Sailor'),
 ('character','Dream Interpreter'),
 ('character','Lab Technician'),
 ('character','Ferry Captain'),
 ('character','Young Caretaker'),
 ('character','Court Artist'),
 ('character','Secretly Ill Monarch'),
 ('character','Unreliable Witness'),
 ('character','Absent-Minded Inventor'),
 ('era','Late Victorian Britain'),
 ('era','Edwardian Era'),
 ('era','Early 20th Century Caribbean'),
 ('era','Pre-Colonial West Africa'),
 ('era','Ming Dynasty China'),
 ('era','Tang Dynasty China'),
 ('era','Joseon Korea'),
 ('era','Achaemenid Persia'),
 ('era','Mughal India'),
 ('era','Song Dynasty China'),
 ('era','Ottoman Golden Age'),
 ('era','Ancient Nubia'),
 ('era','Kingdom of Mali'),
 ('era','Pre-Columbian Caribbean'),
 ('era','Post-Emancipation Caribbean'),
 ('era','Post-Independence Caribbean'),
 ('era','Golden Age of Piracy'),
 ('era','Interwar Europe'),
 ('era','1960s Caribbean'),
 ('era','1970s New York'),
 ('era','1990s Port of Spain'),
 ('era','Near-Future Island Nations'),
 ('era','Early Space Colonization'),
 ('era','Retrofuturist 1980s'),
 ('era','Far-Future Diaspora'),
 ('era','Pre-Industrial Port City'),
 ('era','Ancient Alexandria'),
 ('era','Victorian Caribbean'),
 ('era','Belle Époque'),
 ('era','Future After Climate Change'),
 ('format','Dual POV'),
 ('format','Single POV'),
 ('format','Rotating Ensemble POV'),
 ('format','Epistolary Novel'),
 ('format','Diary Entries'),
 ('format','Recovered Manuscript'),
 ('format','Chat Log Fiction'),
 ('format','Found Footage Narrative'),
 ('format','Oral History'),
 ('format','Verse Novel'),
 ('format','Nonlinear Chapters'),
 ('format','Multiple Timelines'),
 ('format','Framed Narrative'),
 ('format','Vignette Collection'),
 ('format','Serialized Novella'),
 ('format','Short Story Cycle'),
 ('format','Microfiction'),
 ('format','Prose Poetry'),
 ('format','Three-Act Stage Play'),
 ('format','One-Act Play'),
 ('format','Audio Drama Script'),
 ('format','Illustrated Prose'),
 ('format','Four-Panel Comic'),
 ('format','Silent Comic'),
 ('format','Vertical Scroll Comic'),
 ('format','Choose Your Path'),
 ('format','Experimental Second Person'),
 ('format','Unreliable First Person'),
 ('format','Unsent Letters'),
 ('format','Mock Documentary'),
 ('identity','Caribbean Diaspora'),
 ('identity','Afro-Caribbean Lead'),
 ('identity','Indo-Caribbean Lead'),
 ('identity','Mixed-Heritage Protagonist'),
 ('identity','Black Queer Protagonist'),
 ('identity','Asexual Protagonist'),
 ('identity','Aromantic Protagonist'),
 ('identity','Transmasculine Lead'),
 ('identity','Transfeminine Lead'),
 ('identity','Nonbinary Lead'),
 ('identity','Genderfluid Lead'),
 ('identity','Bisexual Lead'),
 ('identity','Sapphic Lead'),
 ('identity','Achillean Lead'),
 ('identity','Deaf Lead'),
 ('identity','Hard of Hearing Lead'),
 ('identity','Blind Lead'),
 ('identity','Disabled Lead'),
 ('identity','Chronically Ill Lead'),
 ('identity','Neurodivergent Lead'),
 ('identity','Older Woman Protagonist'),
 ('identity','Older LGBTQ+ Characters'),
 ('identity','Immigrant Protagonist'),
 ('identity','First-Generation Student'),
 ('identity','Single-Parent Family'),
 ('identity','Adoptive Family'),
 ('identity','Multilingual Cast'),
 ('identity','Diaspora Family'),
 ('identity','Caribbean Folklore Representation'),
 ('identity','Queer Elders'),
 ('warning','Parental Death'),
 ('warning','Sibling Death'),
 ('warning','Pet Death'),
 ('warning','Displacement'),
 ('warning','Forced Migration'),
 ('warning','Serious Illness'),
 ('warning','Grief and Mourning'),
 ('warning','Natural Disaster'),
 ('warning','Colonial Violence'),
 ('warning','Institutional Discrimination'),
 ('warning','Transphobia Depicted'),
 ('warning','Homophobia Depicted'),
 ('warning','Racism Depicted'),
 ('warning','War Aftermath'),
 ('warning','Separation from Family'),
 ('warning','Medical Trauma'),
 ('warning','Religious Trauma'),
 ('warning','Unreliable Memories'),
 ('warning','Gaslighting Depicted'),
 ('warning','Death of a Mentor'),
 ('warning','Childhood Neglect'),
 ('warning','Domestic Abuse Mentioned'),
 ('warning','Drowning References'),
 ('warning','Fire Disaster'),
 ('warning','Panic Attacks Depicted'),
 ('accessibility','Alt Text Included'),
 ('accessibility','All Dialogue Transcribed'),
 ('accessibility','Image Descriptions Available'),
 ('accessibility','Low Motion Visuals'),
 ('accessibility','No Flashing Images'),
 ('accessibility','High Contrast Layout'),
 ('accessibility','Screen Reader Tested'),
 ('accessibility','Plain Language Summary'),
 ('accessibility','Chapter Navigation Landmarks'),
 ('accessibility','Audio Description Included'),
 ('accessibility','Accessible Comic Panel Order'),
 ('accessibility','Captioned Audio'),
 ('accessibility','Keyboard Navigable Experience'),
 ('accessibility','Text-Only Alternative'),
 ('accessibility','Content Advisory Present'),
 ('accessibility','Readable Serif Option'),
 ('accessibility','Large Text Friendly'),
 ('accessibility','Accessible Colour Palette'),
 ('accessibility','Transcribed Visual Poem'),
 ('accessibility','Described Charts'),
 ('additional','Caribbean Folklore'),
 ('additional','Island Carnival'),
 ('additional','Sea Myths'),
 ('additional','Moon Festival'),
 ('additional','Tea Ceremony'),
 ('additional','Oral Storytelling'),
 ('additional','Family Reunion'),
 ('additional','Cultural Preservation'),
 ('additional','Archival Discovery'),
 ('additional','Royal Correspondence'),
 ('additional','Climate Resilience'),
 ('additional','Lost Languages'),
 ('additional','Community Theatre'),
 ('additional','Historical Research'),
 ('additional','Magical Inheritance'),
 ('additional','Court Politics'),
 ('additional','Diplomatic Intrigue'),
 ('additional','Underwater Ruins'),
 ('additional','Moonlit Garden'),
 ('additional','Impossible Library'),
 ('additional','Whispering Forest'),
 ('additional','Haunted Portrait'),
 ('additional','False Prophecy'),
 ('additional','Time Displacement'),
 ('additional','Parallel Histories'),
 ('additional','Found Letters'),
 ('additional','Theatrical Satire'),
 ('additional','Puzzle Mystery'),
 ('additional','Ghost Employees'),
 ('additional','Cursed Document'),
 ('additional','Regency Dance'),
 ('additional','Fandom Crossover'),
 ('additional','Multiple POV Timeline'),
 ('additional','Royal Rivalry'),
 ('additional','Healing Journey'),
 ('additional','Literary Festival'),
 ('additional','Children''s Folktale'),
 ('additional','Mythic Trickster'),
 ('additional','Shipwreck Survival'),
 ('additional','Haunted Lighthouse'),
 ('fandom','The Walking Dead'),
 ('fandom','Stranger Things'),
 ('fandom','Doctor Who'),
 ('fandom','The Lord of the Rings'),
 ('fandom','The Hobbit'),
 ('fandom','Harry Potter'),
 ('fandom','Percy Jackson'),
 ('fandom','The Hunger Games'),
 ('fandom','Game of Thrones'),
 ('fandom','House of the Dragon'),
 ('fandom','Arcane'),
 ('fandom','Avatar The Last Airbender'),
 ('fandom','The Legend of Korra'),
 ('fandom','Demon Slayer'),
 ('fandom','Jujutsu Kaisen'),
 ('fandom','Attack on Titan'),
 ('fandom','Fullmetal Alchemist'),
 ('fandom','Bleach'),
 ('fandom','Dragon Ball'),
 ('fandom','Death Note'),
 ('fandom','My Hero Academia'),
 ('fandom','Chainsaw Man'),
 ('fandom','Spy x Family'),
 ('fandom','Sailor Moon'),
 ('fandom','Studio Ghibli'),
 ('fandom','The Witcher'),
 ('fandom','The Elder Scrolls'),
 ('fandom','Baldur''s Gate'),
 ('fandom','Dragon Age'),
 ('fandom','Mass Effect'),
 ('fandom','The Last of Us'),
 ('fandom','The Legend of Zelda'),
 ('fandom','Final Fantasy'),
 ('fandom','Kingdom Hearts'),
 ('fandom','Resident Evil'),
 ('fandom','Silent Hill'),
 ('fandom','The X-Files'),
 ('fandom','Buffy the Vampire Slayer'),
 ('fandom','Supernatural'),
 ('fandom','Criminal Minds'),
 ('fandom','Law and Order SVU'),
 ('fandom','Grey''s Anatomy'),
 ('fandom','The Vampire Diaries'),
 ('fandom','The Originals'),
 ('fandom','The 100'),
 ('fandom','Downton Abbey'),
 ('fandom','Outlander'),
 ('fandom','Sherlock'),
 ('fandom','Good Omens'),
 ('fandom','Our Flag Means Death'),
 ('fandom','Heartstopper'),
 ('fandom','The Sandman'),
 ('fandom','Dune'),
 ('fandom','The Expanse'),
 ('fandom','SpongeBob SquarePants'),
 ('fandom','Hazbin Hotel'),
 ('fandom','The Owl House'),
 ('fandom','Steven Universe'),
 ('fandom','Gravity Falls'),
 ('fandom','The Untamed'),
 ('fandom','Heaven Official''s Blessing'),
 ('language','Trinidadian English'),
 ('language','Tobagonian Creole'),
 ('language','Trinidad and Tobago English Creole'),
 ('language','Caribbean English Creole'),
 ('language','Jamaican Patois'),
 ('language','Haitian Creole'),
 ('language','French Creole'),
 ('language','Mandarin Chinese'),
 ('language','Cantonese'),
 ('language','Hindi'),
 ('language','Urdu'),
 ('language','Punjabi'),
 ('language','Tamil'),
 ('language','Bengali'),
 ('language','Arabic'),
 ('language','Persian'),
 ('language','Swahili'),
 ('language','Amharic'),
 ('language','Yoruba'),
 ('language','Igbo'),
 ('language','Korean'),
 ('language','Japanese'),
 ('language','Portuguese'),
 ('language','Spanish-English Bilingual'),
 ('language','Multilingual Dialogue')
)
INSERT INTO public.tags(name,category,status,created_by)
SELECT name,category,'canonical',NULL FROM catalogue
WHERE NOT EXISTS (
 SELECT 1 FROM public.tags t
 WHERE t.category=catalogue.category AND lower(t.name)=lower(catalogue.name)
)
ON CONFLICT DO NOTHING;
