import {describe,it,expect} from 'vitest';
import {approvedBadgeFrame,removeConnectedBadgeBackground} from './ApprovedBadgeArt';
import sheets from './approvedBadgeSheets.json';
import badges from './badges.json';
import fs from 'node:fs';

describe('approved achievement paintings',()=>{
 it('maps 100 exact families to 500 distinct, in-bounds tier cells',()=>{
  const seen=new Set();
  expect(Object.keys(sheets)).toHaveLength(100);
  for(const [id,entry] of Object.entries(sheets)){
   expect(badges.find(b=>b.id===id)?.name).toBe(entry.name);
   expect(fs.existsSync('public/assets/palace-courts/'+entry.asset)).toBe(true);
   for(const tier of ['bronze','silver','gold','platinum','emerald']){
    const frame=approvedBadgeFrame({id},tier);
    const [x,y,w,h]=frame.box;
    expect(x).toBeGreaterThanOrEqual(0);expect(y).toBeGreaterThanOrEqual(0);
    expect(x+w).toBeLessThanOrEqual(frame.width+.001);
    expect(y+h).toBeLessThanOrEqual(frame.height+.001);
    seen.add(frame.asset+frame.box.join(','));
    expect(approvedBadgeFrame({id:'database-uuid',name:entry.name},tier)).toEqual(frame);
   }
  }
  expect(seen.size).toBe(500);
 });
 it('finds approved watercolours for all Ink Duel families when their IDs are generated by the database',()=>{
  const mapping={
   'First Bell Scribe':'draft-moon',
   'Keeper of the Arena':'writing-circle-host',
   'Many-Form Quill':'infinite-inkwell',
   'Blind Moon Juror':'sprint-moon',
   'Crowned in Ink':'crown-of-completion',
   'Laurel Constellation':'prompt-collector',
   'Twin Quills Victor':'collaboration-scribe',
   'Court of Eight':'community-host'
  };
  for(const [name,artId] of Object.entries(mapping)){
   for(const tier of ['bronze','silver','gold','platinum','emerald']){
    expect(approvedBadgeFrame({id:'f3a2e6cd-database-id',name},tier)).toEqual(approvedBadgeFrame({id:artId},tier));
   }
  }
 });
 it('does not assign an unrelated illustration to an unknown achievement',()=>{
  expect(approvedBadgeFrame({id:'unknown',name:'Unknown'})).toBeNull();
 });
});

it('keeps crop boundaries between rows instead of cutting by equal sheet divisions',()=>{
 for(const family of Object.values(sheets)){
  expect(family.frames).toHaveLength(5);
  for(const [x,y,w,h] of family.frames){expect(w).toBeGreaterThan(30);expect(h).toBeGreaterThan(30);}
 }
 const shelf=approvedBadgeFrame({id:'collection-curator'},'emerald');
 expect(shelf.box[1]).toBeGreaterThan(1500);
 expect(shelf.box[1]+shelf.box[3]).toBeLessThanOrEqual(shelf.height);
});

it('removes edge-connected dark badge tiles without deleting the isolated painted object',()=>{
 const width=7,height=7,data=new Uint8ClampedArray(width*height*4);
 for(let p=0;p<width*height;p++){const i=p*4;data[i]=12;data[i+1]=20;data[i+2]=35;data[i+3]=255}
 for(let y=2;y<=4;y++)for(let x=2;x<=4;x++){const i=(y*width+x)*4;data[i]=170;data[i+1]=120;data[i+2]=80;data[i+3]=255}
 const image={data};
 removeConnectedBadgeBackground(image,width,height,{threshold:40});
 expect(data[3]).toBe(0);
 expect(data[((3*width+3)*4)+3]).toBe(255);
});
