import React,{useEffect,useState}from'react';import{Link}from'react-router-dom';import{useAuth}from'./auth';import{createDraft,getChamberSnapshot,getMyWorks,getPublishedWorks,updateMyProfile,getSettings,updatePrivacy,updateNotifications,getActivity,markNoticeRead,markAllNoticesRead}from'./palaceData';

function State({children,error,loading,empty}){if(loading)return <div className="live-state">Gathering the room beneath the stars…</div>;if(error)return <div className="live-state error-state"><strong>This room could not be gathered.</strong><span>{error}</span></div>;if(empty)return <div className="live-state">{empty}</div>;return children}

export function ChamberLive({Frame}){
 const{session}=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');const[editing,setEditing]=useState(false);const[saving,setSaving]=useState(false);
 const load=()=>{setError('');getChamberSnapshot(session.user.id).then(setData).catch(e=>setError(e.message))};useEffect(load,[session.user.id]);
 async function save(e){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);try{await updateMyProfile(session.user.id,{display_name:f.get('display_name'),title:f.get('title'),bio:f.get('bio'),visibility:f.get('visibility'),message_policy:f.get('message_policy')});setEditing(false);load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const p=data?.profile;
 return <Frame privateArea><State loading={!data&&!error} error={error}>{p&&<><section className="profile-banner" style={p.cover_url?{backgroundImage:`linear-gradient(90deg,#0a0d20cc,#0a0d2066),url("${p.cover_url}")`}:undefined}><div className="profile-orb">{p.avatar_url?<img src={p.avatar_url} alt=""/>:(p.display_name||p.username||'P').slice(0,1).toUpperCase()}</div><div><p className="eyebrow">MY CHAMBER</p><h1>Welcome home, {p.display_name||p.username}.</h1><p>{p.title||'Palace Member'} · @{p.username}</p></div><button className="outline-button" onClick={()=>setEditing(!editing)}>{editing?'Close':'Tend my profile'}</button></section>
 {editing&&<form className="profile-editor" onSubmit={save}><label>Display name<input name="display_name" defaultValue={p.display_name}/></label><label>Palace title<input name="title" defaultValue={p.title||''}/></label><label className="wide">About your world<textarea name="bio" defaultValue={p.bio||''} rows="4"/></label><label>Profile visibility<select name="visibility" defaultValue={p.visibility}><option value="public">Everyone</option><option value="members">Palace members</option><option value="hidden">Hidden</option></select></label><label>Palace Letters<select name="message_policy" defaultValue={p.message_policy}><option value="open">Open</option><option value="requests">Requests first</option><option value="closed">Closed</option></select></label><button disabled={saving}>{saving?'Saving…':'Save chamber profile'}</button></form>}
 <section className="chamber-grid live-grid"><article className="chamber-card feature"><small>CONTINUE READING</small><h2>{data.progress[0]?.works?.title||'Your next story will wait here.'}</h2><p>{data.progress[0]?`${Number(data.progress[0].progress_percent).toFixed(0)}% read · your place is saved privately.`:'When you begin reading, the Palace will remember your place.'}</p><Link to="/reading">Enter Reading Rooms →</Link></article><article className="chamber-card"><small>WRITING CHAMBER</small><h2>{data.works.length?data.works[0].title:'A quiet desk awaits.'}</h2><p>{data.works.length?`${data.works.length} work${data.works.length===1?'':'s'} in your chamber.`:'Begin a draft when a world arrives.'}</p><Link to="/writing">Open chamber →</Link></article><article className="chamber-card"><small>PALACE ACTIVITY</small><h2>{data.notices.filter(n=>n.unread).length} unread</h2><p>{data.notices[0]?.title||'The Palace is quiet for now.'}</p><Link to="/activity">Visit activity room →</Link></article><article className="chamber-card"><small>YOUR BOUNDARIES</small><h2>{data.privacy.reading_activity_visibility==='private'?'Reading stays private.':'Privacy is in your hands.'}</h2><p>Discovery: {data.privacy.discovery_visibility} · Gifts: {data.privacy.gifts_visibility}</p><Link to="/settings">Settings & Privacy →</Link></article></section></>}</State></Frame>
}

export function ReadingLive({Frame}){
 const[works,setWorks]=useState(null);const[error,setError]=useState('');useEffect(()=>{getPublishedWorks().then(setWorks).catch(e=>setError(e.message))},[]);
 return <Frame><section className="room-title reading-head"><p className="eyebrow">STORIES BENEATH ONE SKY</p><h1>Reading Rooms</h1><p className="lede">Discover stories without turning the Palace into a popularity contest. What is published and accessible to you appears here.</p></section><State loading={!works&&!error} error={error} empty={works?.length===0?'The shelves are ready. No stories have been published to them yet.'}>{works?.length>0&&<section className="story-shelf">{works.map(w=><article className="story-row" key={w.id}><div className="story-cover">{w.cover_url?<img src={w.cover_url} alt=""/>:<span>☾</span>}</div><div><p className="story-meta">{w.rating} · {w.language} · {w.completion_status.replaceAll('_',' ')}</p><h2>{w.title}</h2><p>{w.summary||'The author has left this doorway without a summary.'}</p><small>by {w.profiles?.display_name||w.profiles?.username||'Palace writer'}</small></div></article>)}</section>}</State></Frame>
}

export function WritingLive({Frame}){
 const{session}=useAuth();const[works,setWorks]=useState(null);const[error,setError]=useState('');const[title,setTitle]=useState('');const[busy,setBusy]=useState(false);
 const load=()=>getMyWorks(session.user.id).then(setWorks).catch(e=>setError(e.message));useEffect(load,[session.user.id]);
 async function begin(e){e.preventDefault();setBusy(true);setError('');try{await createDraft(session.user.id,title);setTitle('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Frame privateArea><section className="room-title"><p className="eyebrow">MAKE A WORLD</p><h1>Writing Chamber</h1><p className="lede">A private desk first. Publication comes only when you choose it.</p></section><form className="new-work" onSubmit={begin}><label><span>Begin something new</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title your new work" required/></label><button disabled={busy}>{busy?'Opening desk…':'Create private draft'}</button></form><State loading={!works&&!error} error={error} empty={works?.length===0?'Your writing desk is empty. The first page is yours.'}>{works?.length>0&&<section className="draft-list">{works.map(w=><article key={w.id}><div><small>{w.publication_status.toUpperCase()} · {w.visibility.toUpperCase()}</small><h2>{w.title}</h2><p>{w.chapters.length} chapter{w.chapters.length===1?'':'s'} · {w.chapters.reduce((n,c)=>n+(c.word_count||0),0).toLocaleString()} words</p></div><span>{w.completion_status.replaceAll('_',' ')}</span></article>)}</section>}</State></Frame>
}

export function SettingsLive({Frame}){
 const{session}=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');const[saved,setSaved]=useState('');
 useEffect(()=>{getSettings(session.user.id).then(setData).catch(e=>setError(e.message))},[session.user.id]);
 async function save(e){e.preventDefault();setSaved('');setError('');const f=new FormData(e.currentTarget);try{const privacy={discovery_visibility:f.get('discovery_visibility'),reading_activity_visibility:f.get('reading_activity_visibility'),writing_activity_visibility:f.get('writing_activity_visibility'),clubs_visibility:f.get('clubs_visibility'),honours_visibility:f.get('honours_visibility'),gifts_visibility:f.get('gifts_visibility'),follower_counts_visible:f.has('follower_counts_visible'),online_status_visible:f.has('online_status_visible'),recommendation_learning:f.has('recommendation_learning')};const notifications={stories:f.has('stories'),comments:f.has('comments'),messages:f.has('messages'),invitations:f.has('invitations'),clubs:f.has('clubs'),events:f.has('events'),treasury:f.has('treasury'),follows:f.has('follows'),forum:f.has('forum'),archive:f.has('archive'),email_digest:f.has('email_digest')};const[p,n]=await Promise.all([updatePrivacy(session.user.id,privacy),updateNotifications(session.user.id,notifications)]);setData({privacy:p,notifications:n});setSaved('Your Palace boundaries are saved.')}catch(e){setError(e.message)}}
 return <Frame privateArea><section className="room-title"><p className="eyebrow">YOUR PALACE, YOUR BOUNDARIES</p><h1>Settings & Privacy</h1><p className="lede">Privacy is a room you control, not a punishment for participating.</p></section><State loading={!data&&!error} error={error}>{data&&<form className="settings-form" onSubmit={save}><section><h2>Who may see your world</h2><div className="settings-grid">{[['discovery_visibility','Discover my profile'],['reading_activity_visibility','Reading activity'],['writing_activity_visibility','Writing activity'],['clubs_visibility','Club activity'],['honours_visibility','Honours'],['gifts_visibility','Treasury gifts']].map(([key,label])=><label key={key}>{label}<select name={key} defaultValue={data.privacy[key]}>{(key==='discovery_visibility'?['everyone','members','private']:['public','members','private']).map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}</div><div className="switch-list"><label><input type="checkbox" name="follower_counts_visible" defaultChecked={data.privacy.follower_counts_visible}/> Show follower counts</label><label><input type="checkbox" name="online_status_visible" defaultChecked={data.privacy.online_status_visible}/> Show when I am online</label><label><input type="checkbox" name="recommendation_learning" defaultChecked={data.privacy.recommendation_learning}/> Let my reading improve recommendations</label></div></section><section><h2>What may knock at your door</h2><div className="switch-list two-col">{[['stories','Story updates'],['comments','Comments & replies'],['messages','Palace Letters'],['invitations','Invitations'],['clubs','Clubs'],['events','Events'],['treasury','Royal Treasury'],['follows','New followers'],['forum','Palace Commons'],['archive','Lost Works archive'],['email_digest','Email digest']].map(([key,label])=><label key={key}><input type="checkbox" name={key} defaultChecked={data.notifications[key]}/>{label}</label>)}</div></section><div className="save-row"><button>Save my boundaries</button>{saved&&<span role="status">{saved}</span>}</div></form>}</State></Frame>
}

export function ActivityLive({Frame}){
 const{session}=useAuth();const[items,setItems]=useState(null);const[error,setError]=useState('');const load=()=>getActivity(session.user.id).then(setItems).catch(e=>setError(e.message));useEffect(load,[session.user.id]);
 async function read(id){await markNoticeRead(session.user.id,id);setItems(xs=>xs.map(x=>x.id===id?{...x,unread:false}:x))}
 async function all(){await markAllNoticesRead(session.user.id);setItems(xs=>xs.map(x=>({...x,unread:false})))}
 return <Frame privateArea><section className="room-title activity-head"><p className="eyebrow">NEWS FROM YOUR LITTLE WORLD</p><h1>Moonlight Activity Room</h1><p className="lede">Replies, invitations, follows, publication notices and Palace activity—gathered without turning your attention into a scoreboard.</p></section><div className="activity-tools"><span>{items?.filter(x=>x.unread).length||0} unread</span>{items?.some(x=>x.unread)&&<button className="outline-button" onClick={all}>Mark all read</button>}</div><State loading={!items&&!error} error={error} empty={items?.length===0?'Nothing is calling for your attention right now.'}>{items?.length>0&&<section className="activity-list">{items.map(n=><article key={n.id} className={n.unread?'unread':''} onClick={()=>n.unread&&read(n.id)}><span className="notice-star">{n.unread?'✦':'·'}</span><div><small>{n.notice_type?.replaceAll('_',' ')||'PALACE'}</small><h2>{n.title}</h2>{n.body&&<p>{n.body}</p>}<time>{new Date(n.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</time></div></article>)}</section>}</State></Frame>
}
