import React,{useEffect,useMemo,useState}from'react';
import{getMemberChamberDecor,saveMemberChamberDecor,getPrismState,purchasePrismPalette,selectPrismPalette,savePrismLook}from'./memberChamberDecorData';
import './member-chamber-decor.css';
import './prism-atelier.css';
export const CHAMBER_ORNAMENTS=[['none','Unadorned','·','Included'],['stars','Falling Stars','✧','Included'],['crescent','Crescent Halo','☾','Publish 1 chapter'],['ink-vines','Ink Vines','❦','Publish 500 words'],['silver-branches','Silver Branches','♧','Read 5 rewarded chapters'],['royal-constellation','Royal Constellation','♛','Reach 300 lifetime points']];
export const CHAMBER_LAYOUTS=[['classic','Classic Gallery','▦','Included'],['compact','Collector’s Cabinet','▤','Included'],['spotlight','Spotlight Gallery','✦','Publish 1 chapter']];
const unlocked=(key,u)=>['none','stars','classic','compact'].includes(key)||!!u?.[key];
export function useChamberDecor(memberId){const[decor,setDecor]=useState(null);useEffect(()=>{let active=true;setDecor(null);if(memberId)getPrismState(memberId).then(x=>{if(active)setDecor(x)}).catch(()=>{});return()=>{active=false}},[memberId]);return[decor,setDecor]}
const accents={harmony:null,silver:'#dde7f5',rose:'#f7bad5',mint:'#a7efdb',gold:'#f3d59f'};
const finishes=[['soft','Soft Wash'],['glass','Moon Glass'],['shimmer','Starlit Shimmer'],['lacquer','Royal Lacquer'],['aurora','Aurora Haze']];
const sections=['All','Moon & Night','Ocean','Violet','Rose','Nature','Regalia','Prestige','Legendary'];
export default function MemberChamberDecor({decor,onSaved,own}){
 const[open,setOpen]=useState(false),[palette,setPalette]=useState(null),[family,setFamily]=useState('All'),[category,setCategory]=useState('all'),[finish,setFinish]=useState('soft'),[accent,setAccent]=useState('harmony'),[ornament,setOrnament]=useState('stars'),[layout,setLayout]=useState('classic'),[lookName,setLookName]=useState('My starlit room'),[slot,setSlot]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const catalogue=decor?.prism_catalogue||[];
 useEffect(()=>{if(decor){setPalette(decor.prism_palette||decor.backdrop||'midnight');setFinish(decor.prism_finish||'soft');setAccent(decor.prism_accent||'harmony');setOrnament(decor.ornament||'stars');setLayout(decor.gallery_layout||'classic')}},[decor?.prism_palette,decor?.prism_finish,decor?.prism_accent,decor?.ornament,decor?.gallery_layout]);
 const choice=catalogue.find(x=>x.slug===palette)||catalogue[0];
 const current=catalogue.find(x=>x.slug===decor?.prism_palette);
 const show=catalogue.filter(x=>(family==='All'||x.family===family)&&(category==='all'||category==='owned'&&(x.unlocked)||x.category===category));
 const preview=useMemo(()=>choice?{'--prism-primary':choice.primary,'--prism-secondary':choice.secondary,'--prism-accent':accents[accent]||choice.accent}:undefined,[choice?.slug,accent]);
 const run=async(fn,success)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const next=await fn();const updated=next?.prism_catalogue?next:await getPrismState(decor.user_id);onSaved(updated);setNotice(success||'Your chamber has been updated.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!own||!decor)return null;
 const buy=choice?.category==='treasury'&&!choice.unlocked;
 return <section className="chamber-decorator prism-atelier" aria-label="Prism Atelier"><header><div><p className="eyebrow">THE PRISM ATELIER · 41 CELESTIAL COLOURS</p><h2>Every colour tells a different story.</h2><p>Spin through the spectrum. Preview freely, unlock colours by creating, or collect special hues from the Treasury and tournaments.</p></div><button type="button" onClick={()=>setOpen(v=>!v)}>{open?'Close colour studio':'Open Prism Atelier ✧'}</button></header>
 {open&&<div className="prism-workspace">
 <div className="prism-preview" style={preview} data-finish={finish}><div className="prism-preview-stars" aria-hidden="true">✧　✦　☾</div><span>YOUR CHAMBER · LIVE PREVIEW</span><strong>{choice?.name||'Midnight Velvet'}</strong><p>Somewhere between a story and a constellation.</p><div className="prism-preview-pills"><span>♛ Celestial title</span><span>✧ Achievement gallery</span></div><small>{choice?.unlocked?'Available to wear':choice?.category==='treasury'?choice.price+' points · one-time purchase':'Preview only · '+(choice?.category||'locked')}</small></div>
 <div className="prism-main"><div className="prism-palette-column"><h3>Choose a colour family</h3><div className="prism-families" role="group" aria-label="Colour families">{sections.map(x=><button key={x} type="button" className={family===x?'active':''} aria-pressed={family===x} onClick={()=>setFamily(x)}>{x}</button>)}</div><div className="prism-categories" role="group" aria-label="Colour availability">{[['all','All 41'],['free','Founding'],['earned','Earned'],['treasury','Treasury'],['prestige','Tournaments'],['legendary','Legendary'],['owned','Unlocked']].map(([id,label])=><button key={id} className={category===id?'active':''} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div>
 <div className="prism-palette-grid">{show.map(x=><button type="button" key={x.slug} className={'prism-swatch '+(palette===x.slug?'selected':'')} aria-pressed={palette===x.slug} onClick={()=>setPalette(x.slug)} title={x.description}><span className="prism-swatch-colour" style={{background:'linear-gradient(135deg,'+x.primary+','+x.secondary+')'}}/><strong>{x.name}</strong><small>{x.unlocked?'✦ Available':x.category==='treasury'?'◇ '+x.price+' pts':'♧ Locked · '+x.category}</small></button>)}</div>{!show.length&&<p className="prism-empty">No colours in this part of the constellation. Try another family.</p>}</div>
 <aside className="prism-settings"><h3>Your finishing touches</h3><p className="prism-detail">{choice?.description||'Select a colour to see its story.'}</p><label>Finish<select value={finish} onChange={e=>setFinish(e.target.value)}>{finishes.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Accent colour<select value={accent} onChange={e=>setAccent(e.target.value)}>{[['harmony','Palette harmony'],['silver','Moon silver'],['rose','Roseglass'],['mint','Celadon mint'],['gold','Regal gold']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Ornament<select value={ornament} onChange={e=>setOrnament(e.target.value)}>{CHAMBER_ORNAMENTS.map(([id,name,,condition])=><option key={id} value={id} disabled={!unlocked(id,decor.unlocks)}>{name}{unlocked(id,decor.unlocks)?'':' · '+condition}</option>)}</select></label><label>Gallery layout<select value={layout} onChange={e=>setLayout(e.target.value)}>{CHAMBER_LAYOUTS.map(([id,name,,condition])=><option key={id} value={id} disabled={!unlocked(id,decor.unlocks)}>{name}{unlocked(id,decor.unlocks)?'':' · '+condition}</option>)}</select></label><div className="prism-balance"><span>Available Celestial Points</span><strong>{Number(decor.prism_balance||0).toLocaleString()}</strong></div>
 {buy&&<button type="button" className="prism-purchase" disabled={busy||Number(decor.prism_balance||0)<choice.price} onClick={()=>run(()=>purchasePrismPalette(choice.slug),'Colour collected. It is yours permanently.')} >Purchase {choice.name} · {choice.price} pts</button>}
 <button type="button" className="prism-apply" disabled={busy||!choice?.unlocked} onClick={()=>run(async()=>{await selectPrismPalette(palette,finish,accent);await saveMemberChamberDecor(decor.backdrop,ornament,layout);return getPrismState(decor.user_id)},'Your new chamber is ready ✧')}>{busy?'Saving…':'Apply this look ✦'}</button>
 <p className="prism-disclaimer">Previewing is free. Locked tournament and legendary colours cannot be purchased. No purchases affect Palace rankings.</p>
 </aside></div>
 <div className="prism-looks"><h3>My five saved looks</h3><div><label>Look name<input maxLength={40} value={lookName} onChange={e=>setLookName(e.target.value)}/></label><label>Slot<select value={slot} onChange={e=>setSlot(Number(e.target.value))}>{[1,2,3,4,5].map(i=><option key={i} value={i}>{i}</option>)}</select></label><button type="button" disabled={!choice?.unlocked||busy||lookName.trim().length<2} onClick={()=>run(()=>savePrismLook(slot,lookName,palette,finish,accent),'Look saved.')}>Save selected look</button></div><div className="prism-saved-list">{(decor.prism_looks||[]).map(x=><button key={x.slot} type="button" onClick={()=>{setPalette(x.palette);setFinish(x.finish);setAccent(x.accent)}}><span>0{x.slot}</span><strong>{x.name}</strong><small>Preview ↗</small></button>)}</div></div>
 {notice&&<p role="status" className="prism-notice">{notice}</p>}{error&&<p role="alert" className="prism-error">{error}</p>}
 </div>}
 </section>;
}
