import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {getPalaceGovernance,togglePalaceBallot,createPalaceBallot,publishPalaceNotice} from './palaceGovernanceApi';
import './palace-governance.css';
const formatDate=value=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
export default function PalaceGovernance({Frame}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [view,setView]=useState('ballots'),[filter,setFilter]=useState('open');
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[choices,setChoices]=useState('Yes\nNo'),[hours,setHours]=useState(72),[visibility,setVisibility]=useState('after_close');
 const [noticeTitle,setNoticeTitle]=useState(''),[noticeBody,setNoticeBody]=useState(''),[category,setCategory]=useState('tidings');
 async function load(){setData(await getPalaceGovernance())}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function action(fn,success){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(success)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const ballots=(data?.ballots||[]).filter(b=>filter==='all'||(filter==='open'?b.status==='open'&&new Date(b.opens_at)<=new Date()&&new Date(b.closes_at)>new Date():b.status==='closed'||new Date(b.closes_at)<=new Date()));
 return <Frame privateArea><main className="palace-governance"><header className="governance-hero"><span>♛ THE PALACE COUNCIL · VOICES OF THE COURT</span><h1>The Voting Hall</h1><p>Every member has a voice. Each ballot has clear rules, a closing time, and a documented outcome. Crowns and points never buy additional votes.</p><Link to="/council">Visit the Council review desk →</Link></header>
 <div className="governance-pills"><span>✧ One member, one ballot</span><span>☾ Private individual choices</span><span>✦ Results follow ballot rules</span></div>
 <nav className="governance-tabs" aria-label="Council and voting areas"><button className={view==='ballots'?'active':''} onClick={()=>setView('ballots')}>🗳 Voting Chamber</button><button className={view==='notices'?'active':''} onClick={()=>setView('notices')}>📜 Council Tidings</button>{data?.is_council&&<button className={view==='manage'?'active':''} onClick={()=>setView('manage')}>♛ Council Chamber</button>}</nav>
 {error&&<p className="governance-error" role="alert">{error}</p>}{notice&&<p className="governance-notice" role="status">{notice}</p>}
 {!data&&!error&&<p>Gathering the Council records…</p>}
 {view==='ballots'&&<section><div className="governance-heading"><div><span>YOUR VOICE MATTERS</span><h2>Ballots of the Palace</h2><p>Choose carefully. Change your choice before the ballot closes.</p></div><div className="governance-filter"><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Open</button><button className={filter==='closed'?'active':''} onClick={()=>setFilter('closed')}>Closed</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button></div></div><div className="governance-ballots">{ballots.length?ballots.map(b=>{const open=b.status==='open'&&new Date(b.opens_at)<=new Date()&&new Date(b.closes_at)>new Date();const votes=b.my_votes||[];const total=(b.options||[]).reduce((a,o)=>a+Number(o.votes||0),0);return <article key={b.id} className="governance-ballot"><header><span className={'governance-status '+(open?'live':'finished')}>{open?'✦ VOTING OPEN':'☾ BALLOT CLOSED'}</span><small>{b.ballot_scope==='event'?'Event decision':'Palace decision'}</small><h3>{b.title}</h3><p>{b.description}</p><div className="governance-ballot-meta"><span>Closes {formatDate(b.closes_at)}</span><span>{votes.length}/{b.max_selections} choices</span></div></header><div className="governance-choices">{(b.options||[]).map(o=>{const chosen=votes.includes(o.id);const percent=total?Math.round(Number(o.votes||0)/total*100):0;return <button type="button" disabled={busy||!open||(!chosen&&votes.length>=b.max_selections)} onClick={()=>action(()=>togglePalaceBallot(b.id,o.id),chosen?'Choice withdrawn.':'Your vote is recorded.')} className={'governance-choice '+(chosen?'selected':'')} key={o.id} aria-pressed={chosen}><span><strong>{o.label}</strong>{o.description&&<small>{o.description}</small>}</span><b>{chosen?'✓ Your choice':open?'Select':'—'}</b>{b.results_revealed&&<span className="governance-result"><i style={{width:percent+'%'}}/><em>{o.votes} vote{Number(o.votes)===1?'':'s'} · {percent}%</em></span>}</button>})}</div><footer>{b.results_revealed?<span>{b.voter_count} member{Number(b.voter_count)===1?'':'s'} participated · percentages are by selection</span>:<span>Results {b.results_visibility==='after_vote'?'unlock after you vote':b.results_visibility==='after_close'?'unlock once voting closes':'are hidden'}</span>}<small>Votes cannot be purchased or multiplied with Palace points.</small></footer></article>}):<div className="governance-empty"><strong>✧ The Voting Chamber is peaceful.</strong><p>No ballots match this view. Return for the next Palace decision.</p></div>}</div></section>}
 {view==='notices'&&<section className="governance-notices"><div className="governance-heading"><div><span>SEALED AND PUBLISHED</span><h2>The Council Noticeboard</h2><p>Public-facing news and decisions. Personal reports and evidence are never published here.</p></div></div>{(data?.notices||[]).length?(data.notices||[]).map(n=><article key={n.id}><span>{n.category==='decision'?'⚖ Decision':n.category==='invitation'?'✉ Invitation':'✦ Tidings'}</span><h3>{n.title}</h3><p>{n.body}</p><small>Published {formatDate(n.published_at)}</small></article>):<div className="governance-empty">No Council notices have been published yet.</div>}</section>}
 {view==='manage'&&data?.is_council&&<section className="governance-manage"><div className="governance-heading"><div><span>AUTHORISED STEWARDS ONLY</span><h2>Convene the Council</h2><p>Public ballots and announcements do not replace confidential case reviews.</p></div></div><div className="governance-manage-grid"><form onSubmit={e=>{e.preventDefault();action(()=>createPalaceBallot(title,description,choices.split('\n').map(x=>x.trim()).filter(Boolean),Number(hours),visibility),'A new ballot is open.');}}><h3>🗳 Call a member vote</h3><label>Ballot question<input required minLength={8} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Background and context<textarea required minLength={15} maxLength={1200} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Choices · one per line<textarea required rows={5} value={choices} onChange={e=>setChoices(e.target.value)}/></label><label>Voting period<select value={hours} onChange={e=>setHours(e.target.value)}><option value={24}>24 hours</option><option value={72}>3 days</option><option value={168}>7 days</option><option value={336}>14 days</option></select></label><label>Results visible<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="after_close">After voting closes</option><option value="after_vote">After each member votes</option><option value="public">Throughout voting</option></select></label><button disabled={busy||choices.split('\n').filter(x=>x.trim()).length<2}>Open Palace ballot ✦</button></form><form onSubmit={e=>{e.preventDefault();action(()=>publishPalaceNotice(noticeTitle,noticeBody,category),'The Council notice is published.');}}><h3>📜 Publish Council tidings</h3><label>Notice title<input required minLength={6} maxLength={160} value={noticeTitle} onChange={e=>setNoticeTitle(e.target.value)}/></label><label>Type<select value={category} onChange={e=>setCategory(e.target.value)}><option value="tidings">Council tidings</option><option value="decision">Public decision</option><option value="invitation">Invitation to participate</option></select></label><label>Public wording<textarea required minLength={20} maxLength={2000} rows={7} value={noticeBody} onChange={e=>setNoticeBody(e.target.value)}/></label><p>Never paste private reports, personal data or confidential evidence into a public notice.</p><button disabled={busy}>Publish to the Palace ✧</button></form></div></section>}
 </main></Frame>;
}