import React,{useEffect,useState} from 'react';
import {getCouncilElections,startCouncilElection,nominateCouncilCandidate,castCouncilElectionVote,getCaseChecklists,saveCaseChecklist,reviewCaseAppeal,getCouncilAppealPage,extendCouncilAppeal,escalateCouncilAppeal} from './palaceGovernanceApi';
const reviewFields=[['evidence_checked','Evidence examined'],['context_checked','Context and severity considered'],['member_heard','Member given an opportunity to respond'],['conflict_checked','Reviewer conflicts checked'],['proportionality_checked','Proportionality of recommendation checked'],['appeal_explained','Appeal route documented']];
const blank={categories:[],evidence_checked:false,context_checked:false,member_heard:false,conflict_checked:false,proportionality_checked:false,appeal_explained:false,finding:'pending',action_label:'none',reviewer_note:''};
export function CouncilElections(){const[data,setData]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[statement,setStatement]=useState('');
 const refresh=()=>getCouncilElections().then(setData).catch(e=>setMessage(e.message));
 useEffect(()=>{refresh()},[]);
 const act=async(fn)=>{if(busy)return;setBusy(true);setMessage('');try{await fn();await refresh();setMessage('Council election updated.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <section className="governance-elections"><div className="governance-heading"><div><span>VOICES OF THE TEN PALACES</span><h2>Grand Palace Council elections</h2><p>One representative is chosen by each Palace. Elected representatives advise the community; they do not gain access to confidential moderation files.</p></div>{data?.is_owner&&<button disabled={busy} onClick={()=>act(()=>startCouncilElection('Grand Palace Council Election'))}>Open a new election</button>}</div>
 {message&&<p role="status">{message}</p>}{!data&&<p>Loading your court elections…</p>}
 {(data?.elections||[]).map(e=>{const candidates=e.candidates.filter(c=>c.palace_id===data.my_palace_id);
 return <article className="governance-ballot" key={e.id}><header><small>{e.status.toUpperCase()}</small><h3>{e.title}</h3><p>Nominations close {new Date(e.nominations_close).toLocaleString()} · Voting closes {new Date(e.voting_close).toLocaleString()}</p></header>
 {e.status==='nominations'&&<form className="governance-nomination" onSubmit={ev=>{ev.preventDefault();act(()=>nominateCouncilCandidate(e.id,statement))}}><label>Your candidate statement<textarea minLength={30} maxLength={800} value={statement} onChange={ev=>setStatement(ev.target.value)} placeholder="How would you represent your fellow writers and readers?" required/></label><button disabled={busy||statement.trim().length<30}>Nominate myself</button></form>}
 <div className="governance-choices">{candidates.length?candidates.map(c=><button key={c.candidate_id} className={'governance-choice '+(e.my_vote===c.candidate_id?'selected':'')} type="button" disabled={busy||e.status!=='voting'} onClick={()=>act(()=>castCouncilElectionVote(e.id,c.candidate_id))}><span><strong>{c.display_name||c.username}</strong><small>{c.statement}</small></span><b>{e.status==='closed'?c.votes+' votes':e.my_vote===c.candidate_id?'✓ My vote':'Vote'}</b></button>):<p>No nominees from your Grand Palace yet.</p>}</div><footer>One vote per member per election; vote changes permitted before closing. Tied results require a new election rather than automatic appointment.</footer></article>})}
 {!data?.elections?.length&&data&&<p className="governance-empty">No elections have been called yet. Your Palace's Council voice begins with its first nomination round.</p>}
 </section>}
export function CouncilReviewChecklist(){const[data,setData]=useState(null),[chosen,setChosen]=useState(null),[draft,setDraft]=useState(blank),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [page,setPage]=useState(0),[deadlineReason,setDeadlineReason]=useState(''),[extensionDays,setExtensionDays]=useState(3);const refresh=()=>Promise.all([getCaseChecklists(),getCouncilAppealPage(page)]).then(([cases,queue])=>setData({...cases,appeals:queue.appeals,appealTotal:queue.total,appealPending:queue.pending_total,appealOverdue:queue.overdue_total})).catch(e=>setMessage(e.message));
 useEffect(()=>{refresh()},[page]);
 const run=async(fn)=>{setBusy(true);setMessage('');try{await fn();await refresh();setMessage('Council record saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <section className="governance-checklists"><div className="governance-heading"><div><span>REVIEW BEFORE JUDGMENT</span><h2>Offence review checklist</h2><p>A report is an allegation, not a finding. Every Council assessment must document fairness and evidence. The checklist never automatically suspends a member.</p></div></div>{message&&<p role="status">{message}</p>}
 <div className="governance-review-grid"><div className="governance-review-queue">{(data?.cases||[]).map(c=><button type="button" key={c.report_id} className={chosen===c.report_id?'active':''} onClick={()=>{setChosen(c.report_id);setDraft({...blank,...(c.assessment||{})});}}><strong>{c.reason}</strong><small>{c.status} · {c.target_kind}</small></button>)}{data&&!data.cases.length&&<p>No case reports pending assessment.</p>}</div>
 {chosen&&<form className="governance-review-form" onSubmit={e=>{e.preventDefault();run(()=>saveCaseChecklist({...draft,report_id:chosen}))}}><h3>Case assessment</h3><label>Offence category<select value={draft.categories?.[0]||''} onChange={e=>setDraft(d=>({...d,categories:e.target.value?[e.target.value]:[]}))}><option value="">Not yet classified</option>{['harassment','hate','threats','sexual_content','spam','plagiarism','impersonation','privacy','other'].map(x=><option value={x} key={x}>{x.replaceAll('_',' ')}</option>)}</select></label>{reviewFields.map(([key,label])=><label key={key} className="governance-check"><input type="checkbox" checked={!!draft[key]} onChange={e=>setDraft(d=>({...d,[key]:e.target.checked}))}/>{label}</label>)}
 <label>Finding<select value={draft.finding} onChange={e=>setDraft(d=>({...d,finding:e.target.value}))}><option value="pending">Pending assessment</option><option value="unsubstantiated">Unsubstantiated</option><option value="inconclusive">Inconclusive</option><option value="substantiated">Substantiated</option></select></label><label>Recommended action<select value={draft.action_label} onChange={e=>setDraft(d=>({...d,action_label:e.target.value}))}><option value="none">No action</option><option value="guidance">Guidance</option><option value="warning_recommended">Recommend warning</option><option value="restriction_recommended">Recommend restriction</option><option value="escalation_recommended">Escalate to senior moderation</option></select></label>
 <label>Reviewer's reasoning<textarea rows={5} maxLength={2000} value={draft.reviewer_note} onChange={e=>setDraft(d=>({...d,reviewer_note:e.target.value}))}/></label><button disabled={busy}>Save confidential checklist</button></form>}</div>
 <div className="governance-heading"><div><span>SECOND REVIEW</span><h2>Appeals before the Council</h2><p>{data?.appealPending||0} unresolved · {data?.appealOverdue||0} overdue · {data?.appealTotal||0} total</p></div></div><div className="governance-review-queue">{(data?.appeals||[]).map(a=><article key={a.id}><strong>{a.status.replaceAll('_',' ')}</strong><p>{a.appeal_text}</p><small>Review target: {new Date(a.review_due).toLocaleString()} {new Date(a.review_due)<new Date()&&['submitted','reviewing'].includes(a.status)?'· OVERDUE':''}</small>{a.escalated_at&&<p>✦ Prioritised for independent review</p>}{!a.can_review&&<p className="quiet-copy">Reserved for a different, impartial Council reviewer.</p>}{['submitted','reviewing'].includes(a.status)&&<><textarea rows={3} value={chosen==='appeal:'+a.id?note:''} onChange={e=>{setChosen('appeal:'+a.id);setNote(e.target.value)}} placeholder="Reasoned outcome (25 characters minimum)"/><div className="governance-appeal-actions">{[['reviewing','Reviewing'],['upheld','Uphold'],['changed','Change decision'],['dismissed','Dismiss']].map(([key,label])=><button type="button" key={key} disabled={busy||!a.can_review||(key!=='reviewing'&&note.trim().length<25)} onClick={()=>run(()=>reviewCaseAppeal(a.id,key,chosen==='appeal:'+a.id?note:''))}>{label}</button>)}</div>{a.can_review&&<div className="governance-appeal-actions"><label>Extension days <select value={extensionDays} onChange={e=>setExtensionDays(Number(e.target.value))}>{[1,2,3,4,5,6,7].map(d=><option key={d} value={d}>{d} days</option>)}</select></label><textarea value={chosen==='deadline:'+a.id?deadlineReason:''} onChange={e=>{setChosen('deadline:'+a.id);setDeadlineReason(e.target.value)}} placeholder="Reason for extension or escalation (25+ characters)"/><button type="button" disabled={busy||a.extension_count>0||deadlineReason.trim().length<25||chosen!=='deadline:'+a.id} onClick={()=>run(()=>extendCouncilAppeal(a.id,extensionDays,deadlineReason))}>Extend once</button>{a.overdue&&!a.escalated_at&&<button type="button" disabled={busy||deadlineReason.trim().length<25||chosen!=='deadline:'+a.id} onClick={()=>run(()=>escalateCouncilAppeal(a.id,deadlineReason))}>Flag overdue</button>}</div>}</>}</article>)}{data&&!data.appeals.length&&<p>There are no appeals awaiting review.</p>}</div>{data?.appealTotal>30&&<div className="governance-appeal-actions"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}>Previous</button><span>Page {page+1}</span><button disabled={(page+1)*30>=data.appealTotal} onClick={()=>setPage(p=>p+1)}>Next</button></div>}
 </section>}
