import React,{useEffect,useState} from 'react';
import {getCouncilService,updateCouncilService,logCouncilService,getMyRestoration,respondRestoration,getCouncilRestorationQueue,openRestorationCase,reviewRestoration} from './palaceGovernanceApi';
import './palace-council-accountability.css';
function ActionMessage({message}){return message?<p role="status" className="council-accountability-note">{message}</p>:null}
export function CouncilService(){
 const [data,setData]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[priorities,setPriorities]=useState(''),[availability,setAvailability]=useState(''),[kind,setKind]=useState('listening_session'),[title,setTitle]=useState(''),[summary,setSummary]=useState('');
 const refresh=()=>getCouncilService().then(setData).catch(e=>setMessage(e.message));useEffect(()=>{refresh()},[]);
 const act=async(fn)=>{setBusy(true);setMessage('');try{await fn();await refresh();setMessage('Council service record updated.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <section className="council-accountability"><div className="governance-heading"><div><span>THE PUBLIC RECORD OF SERVICE</span><h2>Our Palace representatives</h2><p>Members can see their representatives' priorities, completed activities, and proposals. Self-reported activities are marked as such; this is not an automated performance score.</p></div></div><ActionMessage message={message}/>
 <div className="council-service-grid">{(data?.representatives||[]).map(r=><article key={r.palace_id} style={{borderTopColor:r.palace_accent||'#9783be'}}><span className="council-service-sigil">♛</span><small>{r.palace_name}</small><h3>{r.display_name||r.username}</h3><p>{r.priorities||r.candidate_statement||'Public priorities have not been posted.'}</p>{r.availability_note&&<small>{r.availability_note}</small>}<div className="council-service-metrics"><span>{r.motion_count} proposals</span><span>{r.service_count} service posts</span></div><details><summary>Service history</summary>{(r.recent_entries||[]).length?r.recent_entries.map(e=><p key={e.id}><strong>{e.title}</strong> · {e.activity_type.replaceAll('_',' ')} — {e.summary}</p>):<p>No service activities recorded yet.</p>}</details></article>)}</div>{data&&!data.representatives.length&&<p className="governance-empty">Council profiles appear after elections are certified.</p>}
 {data?.my_representative_id&&<div className="council-accountability-forms"><form onSubmit={e=>{e.preventDefault();act(()=>updateCouncilService(priorities,availability))}}><h3>Update my representative profile</h3><label>Public priorities<textarea minLength={20} maxLength={500} required value={priorities} onChange={e=>setPriorities(e.target.value)}/></label><label>Availability (optional)<input maxLength={220} value={availability} onChange={e=>setAvailability(e.target.value)}/></label><button disabled={busy}>Save public profile</button></form><form onSubmit={e=>{e.preventDefault();act(()=>logCouncilService(kind,title,summary))}}><h3>Record service activity</h3><label>Activity type<select value={kind} onChange={e=>setKind(e.target.value)}>{['listening_session','creative_event','accessibility','motion_update','community_support'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Title<input required minLength={8} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>What took place?<textarea required minLength={30} maxLength={1000} value={summary} onChange={e=>setSummary(e.target.value)}/></label><button disabled={busy}>Publish activity record</button></form></div>}</section>
}
export function MyCouncilRestoration(){const [data,setData]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[active,setActive]=useState(null),[response,setResponse]=useState(''),[accept,setAccept]=useState(false);
 const refresh=()=>getMyRestoration().then(setData).catch(e=>setMessage(e.message));useEffect(()=>{refresh()},[]);
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{await respondRestoration(active,response,accept);setActive(null);setResponse('');await refresh();setMessage('Your response has been recorded privately.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="council-accountability"><div className="governance-heading"><div><span>DIGNITY AND DUE PROCESS</span><h2>My Council notices</h2><p>Private notices are not public offender labels. You can respond to a finding and choose whether to accept voluntary restoration steps.</p></div></div><ActionMessage message={message}/>
 <div className="governance-notices">{(data||[]).map(c=><article key={c.report_id}><small>{c.severity} · {c.stage}</small><h3>Private review notice</h3><p>{c.notice}</p><small>Response deadline: {new Date(c.response_due).toLocaleString()}</small>{c.offered_restoration&&<p>Optional restoration: {c.offered_restoration}</p>}{c.subject_response&&<p>Your response: {c.subject_response}</p>}{c.secondary_note&&<p>Independent reviewer: {c.secondary_note}</p>}{c.stage==='notice'&&new Date(c.response_due)>new Date()&&<button onClick={()=>setActive(c.report_id)}>Respond privately</button>}</article>)}</div>{data&&!data.length&&<p className="governance-empty">No private Council notices are on your account.</p>}
 {active&&<form onSubmit={submit} className="council-accountability-form"><label>Your response<textarea required minLength={30} maxLength={2000} value={response} onChange={e=>setResponse(e.target.value)}/></label><label className="council-accept"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/> I voluntarily accept the suggested restoration steps (optional)</label><button disabled={busy||response.trim().length<30}>Send private response</button><button type="button" onClick={()=>setActive(null)}>Cancel</button></form>}</section>}
export function CouncilRestorationDesk(){const [data,setData]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState(''),[subject,setSubject]=useState(''),[severity,setSeverity]=useState('minor'),[recommendation,setRecommendation]=useState('guidance'),[notice,setNotice]=useState(''),[restoration,setRestoration]=useState(''),[reviewNotes,setReviewNotes]=useState({});
 const refresh=()=>getCouncilRestorationQueue().then(setData).catch(e=>setMessage(e.message));useEffect(()=>{refresh()},[]);
 const act=async(fn)=>{setBusy(true);setMessage('');try{await fn();await refresh();setMessage('Private review record updated.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <section className="council-accountability"><div className="governance-heading"><div><span>PRIVATE COUNCIL ONLY</span><h2>Accountability & restoration</h2><p>Written findings, a response window and an independent second reviewer are required. These are recommendations, not automatic suspensions.</p></div></div><ActionMessage message={message}/><form className="council-accountability-form" onSubmit={e=>{e.preventDefault();act(()=>openRestorationCase(report,subject,severity,notice,recommendation,restoration))}}><h3>Open reviewed case notice</h3><label>Substantiated report ID<input required value={report} onChange={e=>setReport(e.target.value)}/></label><label>Member account ID<input required value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}>{['minor','moderate','serious','critical'].map(x=><option key={x}>{x}</option>)}</select></label><label>Recommendation<select value={recommendation} onChange={e=>setRecommendation(e.target.value)}>{['guidance','warning','temporary_restriction','escalation'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label>Private notice to member<textarea minLength={30} maxLength={1800} required value={notice} onChange={e=>setNotice(e.target.value)}/></label><label>Optional restorative steps<textarea maxLength={1200} value={restoration} onChange={e=>setRestoration(e.target.value)}/></label><button disabled={busy}>Open private review</button></form><div className="governance-notices">{(data||[]).map(c=><article key={c.report_id}><small>{c.severity} · {c.stage}</small><h3>Case {c.report_id.slice(0,8)}</h3><p>Recommendation: {c.recommendation.replaceAll('_',' ')}</p><p>Response due: {new Date(c.response_due).toLocaleString()}</p>{c.subject_response&&<p>Member response: {c.subject_response}</p>}{c.stage!=='recommendation'&&!c.secondary_reviewer&&<div className="council-accountability-form"><label>Independent review note<textarea minLength={40} maxLength={2000} value={reviewNotes[c.report_id]||''} onChange={e=>setReviewNotes(v=>({...v,[c.report_id]:e.target.value}))}/></label><button disabled={busy||(reviewNotes[c.report_id]||'').trim().length<40} onClick={()=>act(()=>reviewRestoration(c.report_id,reviewNotes[c.report_id]))}>Submit second review</button></div>}</article>)}</div></section>}
