import React,{useEffect,useState} from 'react';
import {getCouncilOutcomes,certifyCouncilElection,castRunoffVote,certifyRunoff,openTieBreak,submitCouncilMotion,getMyCouncilAppeals,submitCaseAppeal} from './palaceGovernanceApi';
export function CouncilResults(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[electionId,setElectionId]=useState(''),[title,setTitle]=useState(''),[reason,setReason]=useState(''),[category,setCategory]=useState('community');
 const load=()=>getCouncilOutcomes().then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 async function act(fn){setBusy(true);setError('');try{await fn();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="council-royal"><div className="governance-heading"><div><span>THE CROWN IS A RESPONSIBILITY</span><h2>The Council of Ten</h2><p>Members elect an advisory representative for each Palace. Tied races go to a runoff; a seat with no valid votes stays vacant. Moderation permissions are never granted by election.</p></div></div>
 {error&&<p role="alert">{error}</p>}
 <div className="council-seat-grid">{(data?.seats||[]).map(s=><article key={s.palace_id}><span>♛</span><small>{s.palace_name}</small><strong>{s.outcome==='elected'?(s.representative||s.username):s.outcome==='runoff'?'Runoff required':'Vacant seat'}</strong>{s.term_ends_at&&<small>Term ends {new Date(s.term_ends_at).toLocaleDateString()}</small>}</article>)}</div>
 {data?.is_owner&&<form className="council-certify" onSubmit={e=>{e.preventDefault();act(()=>certifyCouncilElection(electionId))}}><label>Finished election ID<input value={electionId} onChange={e=>setElectionId(e.target.value)} required/></label><button disabled={busy}>Certify results and open tie-breaks</button></form>}
 <h3>Private Palace runoffs</h3><div className="governance-ballots">{(data?.runoffs||[]).map(r=><article className="governance-ballot" key={r.id}><h3>Palace {r.palace_id} · Round {r.round_number}</h3><p>{r.status} · {new Date(r.closes_at).toLocaleString()}</p><div className="governance-choices">{r.candidates.map(c=><button type="button" key={c.id} className={'governance-choice '+(r.my_vote===c.id?'selected':'')} disabled={busy||r.status!=='open'||new Date(r.closes_at)<=new Date()||data.my_palace_id!==r.palace_id} onClick={()=>act(()=>castRunoffVote(r.id,c.id))}><strong>{c.name||c.username}</strong><span>{r.my_vote===c.id?'✓ My vote':r.status==='open'?'Vote':c.votes+' votes'}</span></button>)}</div>{data.is_owner&&r.status==='awaiting_certification'&&<button disabled={busy} onClick={()=>act(()=>certifyRunoff(r.id))}>Certify runoff</button>}{data.is_owner&&r.status==='tied'&&r.round_number<3&&<button disabled={busy} onClick={()=>act(()=>openTieBreak(r.id))}>Open next tie-break</button>}</article>)}</div>
 <h3>Advisory Council motions</h3>{data?.may_propose&&<form className="governance-nomination" onSubmit={e=>{e.preventDefault();act(()=>submitCouncilMotion(category,title,reason))}}><label>Topic<select value={category} onChange={e=>setCategory(e.target.value)}>{['community','creative','accessibility','events','safety'].map(x=><option key={x}>{x}</option>)}</select></label><label>Title<input required minLength={8} maxLength={140} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Explanation<textarea required minLength={40} maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Submit motion</button></form>}
 <div className="governance-notices">{(data?.motions||[]).map(m=><article key={m.id}><span>{m.category} · {m.status.replaceAll('_',' ')}</span><h3>{m.title}</h3><p>{m.description}</p>{m.decision_note&&<blockquote>{m.decision_note}</blockquote>}</article>)}</div></section>
}
export function MyCouncilAppeals(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[active,setActive]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>getMyCouncilAppeals().then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await submitCaseAppeal(active,reason);setActive(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="council-appeals"><div className="governance-heading"><div><span>SECOND REVIEW</span><h2>My appeals</h2><p>Request another review of a concluded report you submitted. Personal evidence stays private.</p></div></div>{error&&<p role="alert">{error}</p>}
 <div className="governance-notices">{(data?.reports||[]).map(r=><article key={r.id}><small>{r.status}</small><h3>{r.reason}</h3>{r.appeal?<><p>Appeal: {r.appeal.status}</p><p>{r.appeal.appeal_text}</p>{r.appeal.review_note&&<blockquote>{r.appeal.review_note}</blockquote>}</>:['resolved','dismissed'].includes(r.status)?<button onClick={()=>setActive(r.id)}>Request review</button>:<p>Awaiting original decision.</p>}</article>)}</div>
 {active&&<form className="governance-nomination" onSubmit={submit}><label>Why should this be reviewed again?<textarea required rows={5} minLength={25} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<25}>Submit appeal</button><button type="button" onClick={()=>setActive(null)}>Cancel</button></form>}</section>
}
