import React,{useEffect,useState}from'react';
import{Link}from'react-router-dom';
import{getPalaceArtsDiscovery,setPalaceQuestInvitesEnabled,sendPalaceQuestInvite,respondPalaceQuestInvite}from'./palaceArtsDiscoveryData';
import{getPalaceGatherings}from'./grandPalaceGatheringsData';
import './palace-arts-discovery.css';
export default function PalaceArtsDiscovery(){
 const[data,setData]=useState(null),[gatherings,setGatherings]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const[recipient,setRecipient]=useState(''),[quest,setQuest]=useState('');
 const refresh=async()=>{const[a,b]=await Promise.all([getPalaceArtsDiscovery(),getPalaceGatherings()]);setData(a);setGatherings(b);setError('')};
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const action=async(name,fn)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();await refresh();setNotice(name+' updated.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const now=new Date();
 const calendar=Array.from({length:3},(_,i)=>{const monthStart=new Date(Date.UTC(now.getUTCFullYear(),Math.floor(now.getUTCMonth()/3)*3+i,1));return{title:['Opening of the Gates','Court of Living Stories','Closing Constellation'][i],month:monthStart.toLocaleString(undefined,{month:'long',timeZone:'UTC'}),date:monthStart.toISOString().slice(0,10),phase:i+1}});
 const myQuests=(gatherings?.collaborations||[]).filter(q=>q.status==='open');
 return <section className="palace-arts-discovery" aria-labelledby="arts-discovery-title"><header><p className="eyebrow">PALACE ARTS · THE LIVING GATHERING</p><h2 id="arts-discovery-title">Find your people. Share your worlds.</h2><p>A rotating exhibition spotlight, a respectful invitation desk, and a ceremonial festival calendar—without popularity contests or purchased placement.</p></header>
 {error&&<p className="grand-notice error" role="alert">{error}</p>}{notice&&<p role="status" className="grand-notice">{notice}</p>}
 <section className="palace-discovery-features"><div><p className="eyebrow">TODAY'S ROTATING EXHIBITION</p><h3>Constellation Spotlight</h3><p>Up to one creative work per participating Palace, selected through a daily rotation.</p></div><div className="palace-discovery-feature-grid">{(data?.featured||[]).length?data.featured.map(piece=><article key={piece.id}><span>✧ {piece.palace_name}</span><h4>{piece.title}</h4><p>{piece.body}</p><small>{piece.author_name||piece.username} · {piece.kind.replaceAll('_',' ')}</small></article>):<p className="palace-discovery-empty">The first exhibition pieces are still gathering. Members can submit work in the Grand Festival section.</p>}</div></section>
 <section className="palace-festival-calendar"><p className="eyebrow">THE PALACE FESTIVAL CALENDAR · UTC</p><h3>Three chapters, one great season</h3><div>{calendar.map(item=><article key={item.date}><span>0{item.phase}</span><div><small>{item.month}</small><h4>{item.title}</h4><p>{item.phase===1?'Meet your court and offer your first creative piece.':item.phase===2?'Celebrate shared poems, art, fiction and imaginative worlds.':'Mark the season’s final creations before the next quarter begins.'}</p></div></article>)}</div><small>Festival dates follow the current calendar quarter. Shared exhibitions refresh monthly.</small></section>
 <section className="palace-invitation-desk"><header><div><p className="eyebrow">THE FRIENDLY INVITATION DESK</p><h3>Gather collaborators, respectfully.</h3><p>Quest invitations are off by default. Only members who opt in can receive invitations, and anyone can decline.</p></div><label className="palace-invite-optin"><input type="checkbox" checked={!!data?.invites_enabled} disabled={busy||!data} onChange={e=>action('Invitation preference',()=>setPalaceQuestInvitesEnabled(e.target.checked))}/> Accept quest invitations</label></header>
 {(data?.invitations||[]).length>0&&<div className="palace-invite-inbox"><h4>Your invitation letters</h4>{data.invitations.map(inv=><article key={inv.id}><div><strong>{inv.title}</strong><p>From {inv.sender} · {inv.prompt}</p><small>{inv.status}</small></div>{inv.status==='pending'&&inv.quest_status==='open'&&<div><button onClick={()=>action('Invitation',()=>respondPalaceQuestInvite(inv.id,true))} disabled={busy}>Accept</button><button onClick={()=>action('Invitation',()=>respondPalaceQuestInvite(inv.id,false))} disabled={busy}>Decline</button></div>}</article>)}</div>}
 <h4>Creators in your court</h4><div className="palace-discovery-creators">{(data?.court_creators||[]).length?data.court_creators.map(creator=><article key={creator.id}><Link to={'/member/'+encodeURIComponent(creator.username)}>{creator.avatar_url?<img src={creator.avatar_url} alt=""/>:<span>☾</span>}<strong>{creator.display_name||creator.username}</strong></Link><p>{creator.bio||'A fellow member of your Palace.'}</p><small>{creator.accepts_invites?'Open to invitations':'Not receiving invites'}</small>{creator.accepts_invites&&<button type="button" onClick={()=>setRecipient(creator.id)} className={recipient===creator.id?'selected':''}>Invite to a quest</button>}</article>):<p className="palace-discovery-empty">More discoverable Palace creators will appear as members join.</p>}</div>
 {recipient&&<div className="palace-invite-compose"><label>Choose an open quest <select value={quest} onChange={e=>setQuest(e.target.value)}><option value="">Select a quest</option>{myQuests.map(q=><option key={q.id} value={q.id}>{q.title}</option>)}</select></label><button type="button" disabled={!quest||busy} onClick={()=>action('Quest invitation',()=>sendPalaceQuestInvite(quest,recipient))}>Send one invitation ✦</button><button type="button" onClick={()=>setRecipient('')}>Cancel</button><small>Maximum three sent per UTC day; existing member boundaries apply.</small></div>}
 </section></section>;
}
