import React,{useEffect,useState} from 'react';
import {getPetitionHall,submitPetition,supportPetition,respondPetition,hidePetition,getPetitionEngagement,logPetitionProgress,verifyPetitionDelivery} from './palaceGovernanceApi';
import './palace-petitions.css';
const niceDate=x=>new Date(x).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
export default function PalacePetitions(){
 const [engagement,setEngagement]=useState(null),[stage,setStage]=useState('planned'),[updateText,setUpdateText]=useState(''),[proof,setProof]=useState(''),[verifyNote,setVerifyNote]=useState('');const [data,setData]=useState(null),[page,setPage]=useState(0),[palace,setPalace]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [category,setCategory]=useState('community'),[title,setTitle]=useState(''),[description,setDescription]=useState('');
 const [editing,setEditing]=useState(null),[decision,setDecision]=useState('acknowledged'),[reply,setReply]=useState(''),[hideReason,setHideReason]=useState('');
 async function refresh(){const selected=palace?Number(palace):null;const [value,metrics]=await Promise.all([getPetitionHall(page,selected),getPetitionEngagement(page,selected)]);setData(value);setEngagement(metrics)}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[page,palace]);
 async function act(fn,msg){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();await refresh();setMessage(msg)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="palace-petitions"><header className="petition-hero"><span>✦ THE VOICE OF THE PALACES</span><h2>Petitions & Public Record</h2><p>Propose a change, gather support from your Grand Palace, and follow each official reply. Support counts are public; the identities of other supporters remain private.</p></header>
 {error&&<p className="petition-feedback" role="alert">{error}</p>}{message&&<p className="petition-feedback" role="status">{message}</p>}
 <div className="petition-stats">{[[engagement?.summary?.total||0,"Petitions"],[engagement?.summary?.reached_milestone||0,"Milestones reached"],[engagement?.summary?.awaiting_first_reply||0,"Awaiting a reply"],[engagement?.summary?.confirmed_deliveries||0,"Verified deliveries"]].map(([value,label])=><div className="petition-stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="petition-layout"><form className="petition-panel petition-compose" onSubmit={e=>{e.preventDefault();act(()=>submitPetition(category,title,description),'Your petition has entered the Palace record.')}}><h3>✍ Raise a petition</h3><p>Your Palace is assigned automatically. Personal reports belong in the private Council process, not here.</p><label>Topic<select value={category} onChange={e=>setCategory(e.target.value)}>{['community','creative','accessibility','events','platform','other'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><label>Title<input required value={title} minLength={12} maxLength={140} onChange={e=>setTitle(e.target.value)}/></label><label>Tell the Palace what should change<textarea rows={6} required minLength={50} maxLength={1800} value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy||!data?.my_palace_id}>Submit to the Council ✦</button>{!data?.my_palace_id&&data&&<small>Join your Grand Palace to submit or support petitions.</small>}</form>
 <div className="petition-board"><div className="petition-topline"><div><span>THE PEOPLE HAVE SPOKEN</span><h3>Petition Register</h3></div><label>Grand Palace<select value={palace} onChange={e=>{setPalace(e.target.value);setPage(0)}}><option value="">All ten Palaces</option>{(data?.palaces||[]).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div>
 {(data?.petitions||[]).map(p=>{const supportingAllowed=data.my_palace_id===p.palace_id&&!['hidden','closed','declined','implemented'].includes(p.status)&&new Date(p.support_closes_at)>new Date();const progress=Math.min(100,Math.round(100*p.support_count/Math.max(1,p.support_goal)));const place=data.palaces.find(x=>x.id===p.palace_id);const milestone=(engagement?.progress||[]).find(x=>x.petition_id===p.id);
 return <article className="petition-panel petition-card" key={p.id}><div className="petition-card-head"><span>{place?.sigil||'✧'} {place?.name||'Grand Palace'}</span><small>{p.category} · {niceDate(p.submitted_at)}</small></div><h3>{p.title}</h3><p>{p.description}</p><div className="petition-milestone"><div><strong>{p.support_count} supporters</strong><small>{p.support_goal} supporters for a community milestone — not automatic approval</small></div><div className="petition-progress"><i style={{width:progress+'%'}}/></div></div><div className="petition-actions"><span className="petition-status">{p.status.replaceAll('_',' ')}</span><button type="button" disabled={busy||!supportingAllowed||p.mine} aria-pressed={p.supported_by_me} onClick={()=>act(()=>supportPetition(p.id),p.supported_by_me?'Support withdrawn.':'Support recorded.')}>{p.supported_by_me?'✦ Supported':'☆ Support petition'}</button></div><small>Support closes {niceDate(p.support_closes_at)}</small>{milestone&&<div className="petition-deadlines"><strong>{milestone.milestone_reached_at?"✦ Community milestone achieved":"☾ Gathering support"}</strong><span>{milestone.reply_state==="answered"?"Council response recorded":milestone.reply_state==="overdue"?"Council response target overdue":"First Council reply target: "+niceDate(milestone.first_response_due)}</span>{milestone.progress_update_due&&<small>Next public progress update target: {niceDate(milestone.progress_update_due)}</small>}</div>}
 {p.response_text&&<blockquote><strong>♛ {p.responder_role==='steward'?'Palace Steward':'Elected Representative'} · {p.decision}</strong><p>{p.response_text}</p><small>{niceDate(p.responded_at)}</small></blockquote>}
 {milestone&&<details className="petition-timeline"><summary>✧ Public progress timeline</summary>{(milestone.updates||[]).map(u=><article key={u.id}><strong>{u.stage.replaceAll('_',' ')} {u.owner_confirmed?'· Owner verified':'· Reported'}</strong><small>{niceDate(u.at)}</small><p>{u.summary}</p>{u.proof_url&&<a href={u.proof_url} target="_blank" rel="noopener noreferrer">View supporting link ↗</a>}{u.owner_confirmed&&<p>Verification: {u.verification_note}</p>}{data.is_owner&&u.stage==='delivered'&&!u.owner_confirmed&&u.proof_url&&<div><textarea minLength={30} maxLength={600} placeholder="Evidence checked and verification reasoning (30+ characters)" value={verifyNote} onChange={e=>setVerifyNote(e.target.value)}/><button disabled={busy||verifyNote.trim().length<30} onClick={()=>act(()=>verifyPetitionDelivery(u.id,verifyNote),'Delivery verification recorded.')}>Confirm evidence</button></div>}</article>)}{!milestone.updates.length&&<p>No progress has been reported yet.</p>}</details>}{(p.history||[]).length>0&&<details><summary>Public activity history</summary>{p.history.map((h,i)=><p key={i}><small>{niceDate(h.at)} — {h.summary}</small></p>)}</details>}
 {p.can_reply&&<details className="petition-progress-form"><summary>✦ Record Council progress</summary><form onSubmit={e=>{e.preventDefault();act(()=>logPetitionProgress(p.id,stage,updateText,proof),'Progress added to the public timeline.')}}><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}>{['planned','working','blocked','delivered'].map(v=><option value={v} key={v}>{v}</option>)}</select></label><label>Progress details<textarea required minLength={40} maxLength={1200} value={updateText} onChange={e=>setUpdateText(e.target.value)}/></label><label>Evidence link (optional)<input type="url" value={proof} onChange={e=>setProof(e.target.value)} placeholder="https://"/></label><button disabled={busy||updateText.trim().length<40}>Publish progress</button></form></details>}{p.can_reply&&<div className="petition-council-reply"><button type="button" onClick={()=>{setEditing(editing===p.id?null:p.id);setReply('');setDecision('acknowledged')}}>♛ {editing===p.id?'Close response':'Reply for Council'}</button>{editing===p.id&&<form onSubmit={e=>{e.preventDefault();act(()=>respondPetition(p.id,decision,reply),'The official response is recorded.')}}><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}>{['acknowledged','under_review','supported','declined','implemented','closed'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label>Public explanation<textarea required rows={4} minLength={40} maxLength={1800} value={reply} onChange={e=>setReply(e.target.value)}/></label><button disabled={busy||reply.trim().length<40}>Publish response</button></form>}</div>}
 {data.is_owner&&<details className="petition-hide"><summary>Owner moderation</summary><label>Why hide this petition?<textarea value={hideReason} onChange={e=>setHideReason(e.target.value)} minLength={25} maxLength={400}/></label><button disabled={busy||hideReason.trim().length<25} onClick={()=>act(()=>hidePetition(p.id,hideReason),'Petition hidden from public view.')}>Hide from public record</button></details>}
 </article>})}
 {data&&!data.petitions.length&&<div className="petition-panel petition-empty">✧ No petitions in this view yet. The first proposal could come from your Palace.</div>}
 <div className="petition-pagination"><button disabled={page===0} onClick={()=>setPage(x=>Math.max(0,x-1))}>← Previous</button><span>Page {page+1} · {data?.total||0} petitions</span><button disabled={(page+1)*20>=(data?.total||0)} onClick={()=>setPage(x=>x+1)}>Next →</button></div></div></div>
 <section className="petition-decisions"><h3>📜 Council Proposals & Decisions</h3><p>Public outcomes from advisory Council motions. Confidential discipline records are excluded.</p><div className="petition-motion-grid">{(data?.public_motions||[]).map(m=><article key={m.id} className="petition-panel"><span>{m.category} · {m.status.replaceAll('_',' ')}</span><h4>{m.title}</h4><p>{m.description}</p>{m.decision_note&&<blockquote>{m.decision_note}</blockquote>}</article>)}{data&&!data.public_motions.length&&<p>No Council motions have been submitted yet.</p>}</div></section>
 </section>
}
