import { supabase } from './supabase';

function needClient(){if(!supabase) throw new Error('The Palace data connection is not configured.');return supabase}
export async function getMyProfile(userId){const{data,error}=await needClient().from('profiles').select('id,username,display_name,title,bio,avatar_url,cover_url,visibility,message_policy').eq('id',userId).single();if(error)throw error;return data}
export async function updateMyProfile(userId,patch){const allowed={display_name:patch.display_name?.trim(),title:patch.title?.trim()||null,bio:patch.bio?.trim()||'',visibility:patch.visibility,message_policy:patch.message_policy};const{data,error}=await needClient().from('profiles').update(allowed).eq('id',userId).select().single();if(error)throw error;return data}
export async function getMyPrivacy(userId){const{data,error}=await needClient().from('privacy_preferences').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;return data}
export async function ensureMyPrivacy(userId){const current=await getMyPrivacy(userId);if(current)return current;const{data,error}=await needClient().from('privacy_preferences').insert({user_id:userId}).select().single();if(error)throw error;return data}
export async function getChamberSnapshot(userId){const [profile,privacy,works,progress,notices]=await Promise.all([
 getMyProfile(userId),ensureMyPrivacy(userId),
 needClient().from('works').select('id,title,slug,publication_status,completion_status,updated_at').eq('author_id',userId).order('updated_at',{ascending:false}).limit(4),
 needClient().from('reading_progress').select('work_id,chapter_id,progress_percent,completed,updated_at,works(id,title,slug,cover_url)').eq('user_id',userId).eq('completed',false).order('updated_at',{ascending:false}).limit(3),
 needClient().from('notifications').select('id,title,body,notice_type,created_at,unread').eq('user_id',userId).eq('dismissed',false).order('created_at',{ascending:false}).limit(4)
]);if(works.error)throw works.error;if(progress.error)throw progress.error;if(notices.error)throw notices.error;return{profile,privacy,works:works.data||[],progress:progress.data||[],notices:notices.data||[]}}
export async function getPublishedWorks(){const{data,error}=await needClient().from('works').select('id,title,slug,summary,rating,language,completion_status,cover_url,last_published_at,profiles!works_author_id_fkey(username,display_name)').eq('publication_status','published').order('last_published_at',{ascending:false}).limit(24);if(error)throw error;return data||[]}
export async function getMyWorks(userId){const{data,error}=await needClient().from('works').select('id,title,slug,summary,publication_status,completion_status,visibility,updated_at,chapters(id,status,word_count)').eq('author_id',userId).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function createDraft(userId,title){const clean=title.trim();if(!clean)throw new Error('Give your work a title first.');const slug=(clean.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'untitled')+'-'+Date.now().toString(36);const{data,error}=await needClient().from('works').insert({author_id:userId,title:clean,slug,publication_status:'draft',visibility:'private'}).select().single();if(error)throw error;return data}

export async function getSettings(userId){const [privacy,notifications]=await Promise.all([ensureMyPrivacy(userId),needClient().from('notification_preferences').select('*').eq('user_id',userId).maybeSingle()]);if(notifications.error)throw notifications.error;let np=notifications.data;if(!np){const created=await needClient().from('notification_preferences').insert({user_id:userId}).select().single();if(created.error)throw created.error;np=created.data}return{privacy,notifications:np}}
export async function updatePrivacy(userId,patch){const{data,error}=await needClient().from('privacy_preferences').update({...patch,updated_at:new Date().toISOString()}).eq('user_id',userId).select().single();if(error)throw error;return data}
export async function updateNotifications(userId,patch){const{data,error}=await needClient().from('notification_preferences').update({...patch,updated_at:new Date().toISOString()}).eq('user_id',userId).select().single();if(error)throw error;return data}
export async function getActivity(userId){const{data,error}=await needClient().from('notifications').select('id,title,body,notice_type,route_name,route_param,unread,saved,created_at').eq('user_id',userId).eq('dismissed',false).order('created_at',{ascending:false}).limit(50);if(error)throw error;return data||[]}
export async function markNoticeRead(userId,id){const{error}=await needClient().from('notifications').update({unread:false,read_at:new Date().toISOString()}).eq('id',id).eq('user_id',userId);if(error)throw error}
export async function markAllNoticesRead(userId){const{error}=await needClient().from('notifications').update({unread:false,read_at:new Date().toISOString()}).eq('user_id',userId).eq('unread',true);if(error)throw error}

export async function getLibrary(userId){const [saved,progress,subs]=await Promise.all([needClient().from('saved_works').select('saved_at,works(id,title,slug,summary,cover_url,completion_status,profiles!works_author_id_fkey(username,display_name))').eq('user_id',userId).order('saved_at',{ascending:false}),needClient().from('reading_progress').select('work_id,chapter_id,progress_percent,completed,updated_at,works(id,title,slug,cover_url)').eq('user_id',userId).order('updated_at',{ascending:false}),needClient().from('story_subscriptions').select('work_id,enabled,frequency,works(id,title,slug)').eq('user_id',userId).eq('enabled',true)]);for(const r of [saved,progress,subs])if(r.error)throw r.error;return{saved:saved.data||[],progress:progress.data||[],subscriptions:subs.data||[]}}
export async function getTagConstellation(){const{data,error}=await needClient().from('tags').select('id,name,category,status,canonical_tag_id').eq('status','approved').order('name').limit(250);if(error)throw error;return data||[]}
export async function getWorksForTag(tagId){const{data,error}=await needClient().from('work_tags').select('position,works(id,title,slug,summary,rating,completion_status,cover_url,publication_status,profiles!works_author_id_fkey(username,display_name))').eq('tag_id',tagId).order('position').limit(50);if(error)throw error;return(data||[]).filter(x=>x.works?.publication_status==='published')}

export async function getPalaceLife(userId){const [clubs,threads,chat,intros]=await Promise.all([needClient().from('clubs').select('id,name,slug,club_type,privacy,description,club_members!inner(user_id,status)').eq('club_members.user_id',userId).eq('club_members.status','active').limit(12),needClient().from('forum_threads').select('id,title,body,room,created_at,profiles!forum_threads_author_id_fkey(username,display_name)').eq('status','active').order('created_at',{ascending:false}).limit(12),needClient().from('public_chat_messages').select('id,body,created_at,profiles!public_chat_messages_author_id_fkey(username,display_name)').eq('status','active').order('created_at',{ascending:false}).limit(12),needClient().from('member_introductions').select('id,title,body,highlighted,created_at,profiles!member_introductions_author_id_fkey(username,display_name)').eq('status','active').order('created_at',{ascending:false}).limit(8)]);for(const r of[clubs,threads,chat,intros])if(r.error)throw r.error;return{clubs:clubs.data||[],threads:threads.data||[],chat:(chat.data||[]).reverse(),introductions:intros.data||[]}}
export async function postMoonlight(userId,body){const text=body.trim();if(!text)throw new Error('Write something before sending it into the room.');const{data,error}=await needClient().from('public_chat_messages').insert({author_id:userId,body:text}).select().single();if(error)throw error;return data}
export async function createForumThread(userId,title,body){const{data,error}=await needClient().from('forum_threads').insert({author_id:userId,title:title.trim(),body:body.trim(),room:'Palace Commons'}).select().single();if(error)throw error;return data}
export async function getLetters(userId){const [members,requests]=await Promise.all([needClient().from('conversation_members').select('conversation_id,joined_at,conversations(id,kind,status,last_message_at,direct_user_a,direct_user_b)').eq('user_id',userId).is('left_at',null),needClient().from('message_requests').select('id,sender_id,recipient_id,intro_text,status,created_at,profiles!message_requests_sender_id_fkey(username,display_name)').eq('recipient_id',userId).eq('status','pending').order('created_at',{ascending:false})]);if(members.error)throw members.error;if(requests.error)throw requests.error;const conversations=members.data||[];const ids=conversations.map(x=>x.conversation_id);let messages=[];if(ids.length){const r=await needClient().from('messages').select('id,conversation_id,sender_id,body,created_at,status').in('conversation_id',ids).eq('status','active').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;messages=r.data||[]}return{conversations,requests:requests.data||[],messages}}
export async function sendLetter(userId,conversationId,body){const text=body.trim();if(!text)throw new Error('Your letter is empty.');const{data,error}=await needClient().from('messages').insert({conversation_id:conversationId,sender_id:userId,body:text}).select().single();if(error)throw error;return data}

export async function getEventsHeritage(userId){const [events,heritage,rsvps,saved]=await Promise.all([needClient().from('events').select('id,title,slug,event_type,summary,starts_at,ends_at,timezone,access_level,participation,accessibility_notes').eq('publication_status','published').order('starts_at',{ascending:true}).limit(30),needClient().from('heritage_observances').select('id,title,slug,summary,why_in_palace,observance_type,community_key,country_code,region_key,month,day,end_month,end_day,recurring,year,context_notes').eq('editorial_status','verified').order('month').order('day').limit(100),userId?needClient().from('event_rsvps').select('event_id,status').eq('user_id',userId):Promise.resolve({data:[],error:null}),userId?needClient().from('user_heritage_calendar').select('observance_id,saved,reminder_enabled').eq('user_id',userId).eq('saved',true):Promise.resolve({data:[],error:null})]);for(const r of[events,heritage,rsvps,saved])if(r.error)throw r.error;return{events:events.data||[],heritage:heritage.data||[],rsvps:rsvps.data||[],saved:saved.data||[]}}
export async function setEventRsvp(userId,eventId,status='going'){const{error}=await needClient().from('event_rsvps').upsert({user_id:userId,event_id:eventId,status,updated_at:new Date().toISOString()},{onConflict:'event_id,user_id'});if(error)throw error}
export async function saveHeritage(userId,observanceId){const{error}=await needClient().from('user_heritage_calendar').upsert({user_id:userId,observance_id:observanceId,saved:true,updated_at:new Date().toISOString()},{onConflict:'user_id,observance_id'});if(error)throw error}
export async function getTreasury(userId){const [ach,gifts,showA,showG,pref]=await Promise.all([needClient().from('user_achievement_progress').select('current_value,bronze_unlocked_at,silver_unlocked_at,gold_unlocked_at,platinum_unlocked_at,emerald_unlocked_at,achievement_families(id,name,description,thresholds,art_status,catalogue_number)').eq('user_id',userId),needClient().from('user_gift_inventory').select('tier,copies,virtual_gifts(id,name,description,court_name,catalogue_number,art_status,upgrade_copies)').eq('user_id',userId).gt('copies',0),needClient().from('profile_achievement_showcase').select('achievement_id,display_tier,position').eq('user_id',userId).order('position'),needClient().from('profile_gift_showcase').select('gift_id,display_tier,position').eq('user_id',userId).order('position'),needClient().from('ranking_preferences').select('*').eq('user_id',userId).maybeSingle()]);for(const r of[ach,gifts,showA,showG,pref])if(r.error)throw r.error;return{achievements:ach.data||[],gifts:gifts.data||[],achievementShowcase:showA.data||[],giftShowcase:showG.data||[],rankingPreferences:pref.data}}
export async function getArchive(){const{data,error}=await needClient().from('archive_records').select('id,accession_number,slug,title,creator_name,record_nature,category,summary,original_language,languages,surviving_extent,known_gaps,provenance_summary,rights_status,hosting_basis,host_mode,continuation_status,verified_at').eq('publication_status','published').order('updated_at',{ascending:false}).limit(100);if(error)throw error;return data||[]}
export async function saveArchiveRecord(userId,recordId){const{error}=await needClient().from('user_archive_records').upsert({user_id:userId,record_id:recordId,saved:true,visited_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id,record_id'});if(error)throw error}

export async function getMemberProfile(username,viewerId){const{data:profile,error}=await needClient().from('profiles').select('id,username,display_name,title,bio,avatar_url,cover_url,visibility,message_policy').eq('username',username).maybeSingle();if(error)throw error;if(!profile)return null;const [privacy,works,follow,counting]=await Promise.all([needClient().from('privacy_preferences').select('discovery_visibility,writing_activity_visibility,honours_visibility,gifts_visibility,follower_counts_visible').eq('user_id',profile.id).maybeSingle(),needClient().from('works').select('id,title,slug,summary,cover_url,completion_status,last_published_at').eq('author_id',profile.id).eq('publication_status','published').order('last_published_at',{ascending:false}).limit(12),viewerId&&viewerId!==profile.id?needClient().from('member_follows').select('followed_id').eq('follower_id',viewerId).eq('followed_id',profile.id).maybeSingle():Promise.resolve({data:null,error:null}),needClient().from('member_follows').select('follower_id',{count:'exact',head:true}).eq('followed_id',profile.id)]);for(const r of[privacy,works,follow,counting])if(r.error)throw r.error;return{profile,privacy:privacy.data,works:works.data||[],following:!!follow.data,followerCount:counting.count||0}}
export async function setFollow(viewerId,memberId,follow){if(follow){const{error}=await needClient().from('member_follows').insert({follower_id:viewerId,followed_id:memberId});if(error)throw error}else{const{error}=await needClient().from('member_follows').delete().eq('follower_id',viewerId).eq('followed_id',memberId);if(error)throw error}}
export async function searchMembers(term){const q=term.trim();if(!q)return[];const{data,error}=await needClient().from('profiles').select('id,username,display_name,title,avatar_url,visibility').or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).neq('visibility','hidden').limit(20);if(error)throw error;return data||[]}
