/*
 * The Starry Palace · darker adult-fiction challenge constellations.
 * 1,000 substantial fictional horror/violence prompts, five story families,
 * 200 unique combinations each. No outside generation or network fetches.
 * Content advisory: murder, brutality, blood, survival, trauma, body horror.
 */
export const ORRERY_DARK_ORBITS={
 'Psychological Terror':{
  genres:['Psychological horror','Unreliable-narrator thriller','Paranoia noir','Claustrophobic suspense','Serial-killer mystery','Hallucinatory horror','Hostage-room drama','Mind-game gothic'],
  objects:['a bloodstained confession tape','a photograph of a crime not yet committed','a key taken from a locked basement','an anonymous note under the mattress','a set of recordings made in different voices','a diary whose pages accuse the reader','a sealed psychiatric case file','a missing floor from a hotel blueprint','a violin case with an ominous weight','a surgical mask marked with a stranger’s name','a clock that ticks only when someone is watching'],
  twists:['the narrator committed the crime they are investigating','the missing victim has become the interrogator','every witness has been carefully rehearsed','the apparent captive is directing the hunt','the killer is a role assigned by the town','the only trustworthy memory belongs to the antagonist','the murderer demands the truth, not forgiveness','the evidence is genuine but the chronology is fabricated','the victim has staged their disappearance for a worse purpose','an accomplice has been posing as the sole survivor','the final confession reveals a second imprisoned person'],
  moods:['brutally tense','unsettling and intimate','coldly paranoid','merciless','feverish','agonisingly quiet','morally corrosive'],
  characters:['a sleepless forensic interviewer','a missing-person investigator','a survivor who cannot recognise their rescuer','a famous criminal profiler','a court stenographer hiding an audio tape','a prisoner assigned to a truth experiment','an undertaker who knows too many secrets','a witness protected by a liar','a troubled surgeon with missing hours'],
  relationships:['a captive and their manipulative captor','siblings who remember the murder differently','a detective and their former mentor','a survivor and a false rescuer','a therapist and a dangerous patient','two suspects forced to cooperate','a parent and a child who share a secret'],
  settings:['a windowless interrogation room','a motel where every guest has an alias','a seaside psychiatric hospital','an abandoned courthouse','a city apartment under constant surveillance','a mountain lodge cut off by a blizzard','a funeral home during a blackout','a prison visitors’ room','a commuter train with no next stop'],
  conflicts:['confessing to the truth would condemn an innocent person','the investigation is designed to break the detective','a character must decide whom to betray before dawn','every escape route leads back to the crime','the last survivor may be the most dangerous','the villain is willing to die to expose an old wrong','a witness must choose between freedom and the truth','rescue would reveal the protagonist’s complicity','the only way out is to remember a violent act']
 },
 'Slasher & Survival':{
  genres:['Slasher horror','Cabin-in-the-woods terror','Home-invasion thriller','Survival horror','Creature-feature siege','Stalker suspense','Grindhouse horror','Escape-room nightmare'],
  objects:['a bloodied axe found beneath the porch','a hunting knife with a missing handle','an emergency radio repeating screams','a smashed security camera','a map scratched into a cell door','a ripped survivor’s jacket','an abandoned rescue flare','a cellar padlock dripping with blood','a cold chainsaw missing its chain','a headlamp with a cracked lens','a trail of muddy footprints ending at a wall'],
  twists:['the killer is trapped inside with the survivors','the safe house is the hunting ground','one survivor has been warning the attacker','the monster knows every rescue plan','the final escape demands a brutal sacrifice','the distress call came from the assailant','a second killer has been following the first','the apparent victim is bait for the others','the killer can mimic a trusted voice','the locked doors were meant to keep something in','sunrise brings a worse threat'],
  moods:['visceral and relentless','desperate','predatory','panic-stricken','bleakly cinematic','savage and urgent','dread-soaked'],
  characters:['a wounded park ranger','a nurse stranded after a road accident','a teenager who knows the escape tunnels','a disgraced wilderness guide','a security guard on their last shift','a missing camper’s sibling','a reluctant emergency dispatcher','a survivor from an earlier massacre','a filmmaker who refuses to stop recording'],
  relationships:['strangers barricaded together','best friends forced to abandon a plan','a parent shielding an adult child','a survivor and an injured pursuer','former rivals sharing the last ammunition','two siblings separated by a locked gate','a group that cannot agree whom to trust'],
  settings:['a flooded basement in a storm','a remote slaughterhouse at midnight','an abandoned amusement park','a woodland summer camp in winter','a ferry stranded offshore','a desert roadside motel','a mountain tunnel with no lights','a closed shopping mall after curfew','a storm-battered coastal village'],
  conflicts:['the only exit passes directly through the killer’s territory','each rescue attempt costs another life','a wounded ally cannot keep up and refuses to be left','the group discovers that one of them set the trap','the weapon they depend upon is missing','the survivors must choose between staying silent and saving strangers','the last vehicle has room for one fewer person','the threat can only be stopped by destroying the shelter','the hunter offers a deal that is almost irresistible']
 },
 'Grimdark & Blood Oaths':{
  genres:['Grimdark fantasy','War-crime gothic','Assassin’s court intrigue','Siege horror','Vengeful dark fantasy','Sword-and-sorcery tragedy','Revolutionary bloodshed','Postwar ruin saga'],
  objects:['a crown seized from a battlefield corpse','a treaty signed in blood','a broken executioner’s sword','a military banner sewn from mourning clothes','a poisoned communion cup','an oath ledger filled with dead names','a prison key traded for bread','a blade forged from a family relic','a captain’s orders with every signature crossed out','a royal ring buried in ash','a map made on the hide of a dead beast'],
  twists:['the liberator becomes a tyrant','the enemy army is trying to protect the civilians','the promised mercy is a trap','the knight’s celebrated victory was a massacre','the rebel leader ordered the atrocity','the ruler is resurrected only to face judgment','the sacred war is being fought over a lie','the assassin is the most loyal person at court','the final siege can be ended only through betrayal','the chosen heir refuses a blood oath','the prophecy demands the victor become the next monster'],
  moods:['ruthless','blood-soaked and tragic','regal and terrifying','vengeful','mercilessly political','morally bleak','defiant amid ruin'],
  characters:['a general haunted by an old massacre','a royal executioner with one last order','a rebel queen facing famine','a mercenary sworn to the wrong cause','a monk who has buried an army','a teenage prince marked for death','a palace torturer seeking absolution','a wounded deserter carrying evidence','a court poet who witnessed treason'],
  relationships:['two rival heirs with a shared enemy','a general and their condemned prisoner','a ruler and their oldest assassin','a parent and child on opposing battle lines','a rebel and their betrayer','a knight and a disillusioned squire','a queen and the historian ordered to glorify her'],
  settings:['a siege camp outside burning city walls','a plague-ridden royal court','an abandoned throne room after a coup','a battlefield at first light','a fortress turned into a prison','a blood-red river crossing','a village awaiting military reprisals','a cathedral after the massacre','a palace banquet on the eve of revolt'],
  conflicts:['justice requires condemning a beloved hero','winning the war will destroy the kingdom','a threatened hostage could avert a second massacre','the victorious side must face what it has done','an assassin must choose between duty and mercy','a rebellion must decide whether revenge is its only law','a ruler must admit their throne was won through murder','survivors demand the truth while generals negotiate peace','a blood oath demands the death of an innocent']
 },
 'Occult & Body Horror':{
  genres:['Body horror','Ritual horror','Cosmic horror','Possession gothic','Necromantic mystery','Occult folk horror','Surgical nightmare','Religious dread fantasy'],
  objects:['a jar containing a human tooth that moves','a stained ritual scalpel','a bone flute beneath a chapel floor','a mirror showing the inside of a person','a locked medical specimen freezer','a black candle that burns red','a stitched book made of unfamiliar skin','a funerary mask that whispers at night','a blood-marked circle in an abandoned cellar','a sealed reliquary rattling from within','an anatomy drawing with one impossible organ'],
  twists:['the sacrifice has been chosen by the victim','the body is changing to survive the ritual','the possessed person is trying to contain the spirit','the cult worships something that wants to be left alone','the dead return wearing the wrong faces','the healer is responsible for the disease','the monstrous transformation carries an unbearable truth','the ritual opens a door inside the host','the creature is assembled from remembered grief','the gods have been replaced by hungry impostors','the surviving priest has never been human'],
  moods:['grotesque and solemn','ritually oppressive','uncanny','flesh-crawling','sacrilegious and eerie','cosmically hopeless','viscerally surreal'],
  characters:['a surgical resident witnessing an impossible procedure','a mortician restoring an unidentifiable body','a priest who no longer believes','a botanist infected by a strange bloom','a former cult initiate','a coroner with a forbidden book','a medium whose visions leave scars','a village healer with one final patient','an apprentice embalmer'],
  relationships:['a healer and a patient undergoing transformation','siblings marked by the same curse','a devotee and their false god','a priest and the voice beneath the altar','a victim and their future self','two cult escapees hiding a secret','an anatomist and the body they cannot explain'],
  settings:['a chapel beneath a hospital','a subterranean ritual chamber','a coastal cemetery during a red tide','an abandoned operating theatre','a mountain monastery after a plague','a forest shrine hung with bone charms','a museum of forbidden relics','a drowned crypt below a palace','a house whose walls seem to breathe'],
  conflicts:['saving a friend requires accepting a terrifying transformation','the ritual can be stopped only by destroying the relic and its keeper','a host must choose whose mind controls their body','the village has mistaken the curse for a miracle','a healer discovers the illness has intentions','someone must interrupt a human sacrifice before the final bell','the dead refuse to remain buried until a crime is confessed','the only cure will free a hostile presence','destroying the monster would also kill its unwilling host']
 },
 'Crime & Moral Darkness':{
  genres:['Hardboiled crime noir','Revenge thriller','Underworld tragedy','Organised-crime saga','Violent political thriller','Vigilante noir','Corrupt-police mystery','Kidnapping suspense'],
  objects:['a bloodstained briefcase of photographs','a pistol recovered from a canal','a ledger of secret police payments','a blackmail recording on a damaged cassette','an unmarked grave photograph','a torn confession letter','a key to an illicit holding cell','a suitcase full of evidence tags','a newspaper proof exposing a killing','a false passport with an execution date','a smuggler’s compass marked with names'],
  twists:['the vigilante is protecting the real murderer','the investigation exposes an entire corrupt institution','the kidnapped witness is organising their own escape','the corrupt officer is the only one telling the truth','the revenge target has already been killed','the hit was ordered to prevent a worse atrocity','the informant and the assassin are the same person','the victim planned to expose a war crime','the supposed hero fabricated the evidence','the criminal boss has secretly been saving strangers','the detective becomes the next intended victim'],
  moods:['brutal and unsentimental','tense noir','icy and vengeful','morally compromised','streetwise and desperate','rage-filled','tragically human'],
  characters:['a disgraced homicide detective','a journalist hunting a missing witness','a reluctant contract killer','a police officer refusing an illegal order','a smuggler with an unexpected code','a city councillor under threat','a public defender with secret evidence','a gang member wanting out','a forensic photographer seeking revenge'],
  relationships:['a detective and a former partner turned suspect','a criminal and the sibling they protected','a journalist and their endangered source','a corrupt official and their whistleblower','an assassin and a person they were sent to kill','two enemies trapped by the same syndicate','a parent trying to recover a kidnapped child'],
  settings:['a rain-soaked back alley behind a nightclub','a city courthouse under siege','a ferry terminal with an illicit handoff','a safe house overlooking the harbour','an abandoned police evidence room','a crime scene at a luxury gala','a crowded political rally after an assassination','a smuggler’s warehouse by the sea','a prison transport in a blackout'],
  conflicts:['the only witness will testify if someone else is sacrificed','justice and revenge demand opposing choices','saving a hostage means letting a killer escape','a detective must arrest their own benefactor','the evidence reveals the government ordered the killings','a criminal’s last act of mercy threatens the entire network','protecting a child requires exposing a family crime','the assassin has one hour to prevent a massacre','the protagonist must decide whether to break the law to expose it']
 }
};
export const ORRERY_DARK_RECIPES=Object.entries(ORRERY_DARK_ORBITS).flatMap(([flavour,pool],familyIndex)=>
 Array.from({length:200},(_,index)=>{
  const j=index;
  return{
   id:'orrery-'+String(6013+familyIndex*200+j).padStart(4,'0'),
   flavour,
   intensity:'Mature / Violent',
   genre:pool.genres[(j*5+familyIndex)%pool.genres.length],
   object:pool.objects[(j*7+familyIndex*2)%pool.objects.length],
   twist:pool.twists[(j*3+familyIndex*4)%pool.twists.length],
   mood:pool.moods[(j*5+familyIndex)%pool.moods.length],
   character:pool.characters[(j*2+familyIndex*3)%pool.characters.length],
   relationship:pool.relationships[(j*3+familyIndex*2)%pool.relationships.length],
   setting:pool.settings[(j*5+familyIndex*3)%pool.settings.length],
   conflict:pool.conflicts[(j*7+familyIndex*5)%pool.conflicts.length],
   difficulty:['Standard','Challenging','Grand Challenge'][(j+familyIndex)%3]
  };
 }));
