/*
 * The Starry Palace · 2,000 new Prompt Orrery constellations.
 * Exactly 250 deliberately varied combinations in each of eight craft orbits.
 * Static seeded recipe data: no network requests, generated image assets, or AI.
 */
export const ORRERY_NEW_ORBITS={
 'Folklore & Legends':{
  genres:['Caribbean folk fantasy','West African spirit tale','South Asian mythic adventure','Persian court legend','Chinese folklore mystery','Ethiopian historical fantasy','Indigenous-inspired speculative fable','Mediterranean sea myth'],
  objects:['a calabash carrying a forgotten voice','a silk map of a mountain no longer there','a drum that answers only true questions','a moonstone hidden inside a bread loaf','a pair of sandals left at a sacred crossroads','a carved comb that remembers promises','a market bell that announces arriving legends','an embroidered cloth with a changing coastline','a jar of river water that never stands still'],
  twists:['the trickster has come to ask for forgiveness','the guardian is protecting a terrible truth','the legend has been told from the wrong side','the village elder is the youngest soul there','the mountain has chosen a new keeper','the ritual works, but on the wrong person','a borrowed name must be returned before sunrise','the creature is a person under an ancient obligation','the sacrifice is refused by the one who asked for it','the prophecy is a map, not a prediction','the ancestors disagree about what justice requires'],
  moods:['ritual and wonder','eerie and tender','festive but haunted','epic and intimate','wistful and myth-soaked','bright with hidden danger','quietly sacred'],
  characters:['a reluctant shrine keeper','an apprentice masquerade maker','a fisherman who cannot lie','a royal interpreter','a child who speaks with rivers','a travelling griot','a market vendor who shelters spirits','a historian who doubts legends'],
  relationships:['a trickster and the person they once deceived','a grandmother and her reluctant successor','two rival storytellers','an elder and their returned grandchild','a guardian spirit and a sceptical scholar','estranged siblings guarding the same doorway','a deity and their last believer'],
  settings:['a moonlit shoreline during a harvest festival','a village whose paths rearrange after rain','an ancient caravanserai during an eclipse','a palace courtyard of whispering trees','a rainforest bridge between two seasons','a mountain shrine with no visible entrance','a night market where the dead trade stories','a boat crossing a river of memories'],
  conflicts:['keeping a community safe requires changing its oldest story','an inherited promise has two rightful claimants','a visitor must decide whether to reveal a sleeping spirit','the hero can save their family but not their name','a true account threatens a beloved tradition','a missing ritual piece belongs to someone who refuses to return','a ghost demands a public apology no one wants to give','the guardian wants to retire but the world cannot agree on a replacement','telling the truth might make the legend real']
 },
 'Whodunits & Secrets':{
  genres:['Locked-room mystery','Village noir','Literary conspiracy','Historical detective story','Island-set suspense','Academic mystery','Political intrigue','Domestic mystery'],
  objects:['an unsigned museum acquisition receipt','a diary whose last page is wet','a theatre programme with a missing name','a sealed ballot box','a key wrapped in an apology','an empty photograph frame with a date','a chess clock stopped at midnight','a hotel guest ledger in two inks','an untouched cup at a crowded table'],
  twists:['the victim staged the scene for a different reason','every suspect is protecting the same stranger','the alibi proves a second crime','the true clue is an absence','the witness remembers tomorrow, not yesterday','the forged evidence is more truthful than the original','the investigator has been hired by the culprit','the missing person is hiding in public view','the final witness refuses to be believed','the anonymous tip was written years before the event','the motive changes after the mystery is solved'],
  moods:['intellectually tense','gothic and restrained','sardonic','claustrophobic','melancholy noir','polished and ominous','cosy with a knife edge'],
  characters:['an archivist whose records have been altered','a theatre understudy','a whistleblower with no safe confidant','a retired detective','a community radio presenter','a reluctant jury foreperson','a curator who knows every secret exit','a translator of suspicious letters'],
  relationships:['two investigators who distrust each other','a witness and the accused','a mother and an estranged daughter','rival journalists','an employer and a former assistant','an amateur sleuth and a hostile local officer','siblings named in the same will'],
  settings:['a rain-bound seaside hotel','a museum preparing to reopen','a commuter train stopped between stations','a grand library after closing','an island town during an election','a university reunion dinner','a theatre on the night of its final show','a historical society with a missing archive'],
  conflicts:['solving the mystery will expose a person the investigator wants to protect','an anonymous confession implicates someone already dead','the only reliable timeline contradicts everyone involved','a clue disappears every time it is discussed','the investigator must reveal their own deception','a community prefers a comforting lie to the evidence','each witness has a truthful but incomplete account','the culprit offers to confess to the wrong crime','time is running out before the evidence is destroyed']
 },
 'Everyday Magic':{
  genres:['Contemporary magical realism','Quiet domestic fantasy','Cosy urban fantasy','Neighbourhood fairy tale','Magical workplace comedy','Tender speculative romance','Seasonal slice of life','Small-town wonder'],
  objects:['a library book that remembers its last reader','a kettle that sings when someone is lonely','a bus stop that offers one extra minute','an heirloom measuring spoon','a neighbour’s impossible garden seed','a raincoat lined with constellations','a missing button from a wedding suit','a receipt for one extra ordinary day','a mug that refills only for visitors'],
  twists:['the spell works on everyone except its maker','the miracle is ordinary to the neighbours','the wish comes true one minute at a time','the person in need is the magical object','the enchantment has been passed down as a chore','the miracle will disappear if anyone takes credit','an ordinary mistake is the key to breaking the curse','the old magic stops working when somebody moves away','the magical helper asks for a day off','the magic has become a matter of local bureaucracy','nothing supernatural happens until everyone leaves'],
  moods:['hopeful','gentle and bittersweet','whimsical','intimate','playfully surreal','warmly melancholy','bright with wonder'],
  characters:['a baker between two careers','a single parent running late','a shy bookshop owner','a night-shift cleaner','a grandfather learning to dance','a student living far from home','a florist who hates flowers','a newcomer in an old neighbourhood'],
  relationships:['an elderly neighbour and a new tenant','a parent and their independent child','estranged childhood friends','two strangers sharing a garden','a teacher and an adult former student','a baker and their fiercest critic','a couple learning to live alone together'],
  settings:['a tea shop before its first customers','an apartment courtyard at sunrise','a rainy bus terminal','a Caribbean roadside fruit stall','a library returns desk','a small bakery during a power cut','a community garden on moving day','a ferry in the first light of morning'],
  conflicts:['a tiny magic can solve only one of two honest needs','someone must choose between keeping the wonder and keeping the memory','a beloved neighbourhood place is about to close','two people depend on a miracle they understand differently','the gift is too small to change a life but large enough to start a conversation','an act of kindness has an unexpected cost','a forgotten agreement has become a family ritual','every resident claims to own the same enchanted plant','a character must learn to ask for help']
 },
 'Letters & Confessions':{
  genres:['Epistolary romance','Confessional drama','Historical correspondence','Found-document thriller','Letter-writing fantasy','Unreliable diary fiction','Voice-note storytelling','Archive-room mystery'],
  objects:['an undelivered envelope addressed to two people','a letter with its signature crossed out','a notebook hidden inside a suitcase lining','a bundle of postcards without stamps','a telegram arriving too late','a fountain pen leaking blue ink','a voicemail saved under the wrong name','a sealed envelope with a blank date','a page torn from a ship’s log'],
  twists:['the recipient has been answering under another name','the letters were never supposed to be mailed','two writers are using the same pen name','the confession is true but the story is not','the missing reply contains an invitation','the last message is written by someone absent from the archive','the handwriting changes at a precise moment','the sender is asking to be forgotten','a second set of letters contradicts the first','the final note refuses to conclude the story','a person mistakes an apology for a declaration of love'],
  moods:['achingly intimate','restrained and wistful','tenderly suspenseful','unsettling','romantic but uncertain','elegant and heartbreaking','sharply funny'],
  characters:['a reluctant archivist','a widow restoring old letters','an assistant who knows too much','a long-distance sailor','a novelist with an unfinished manuscript','a soldier returning home','a woman keeping family records','a broadcaster who reads anonymous messages'],
  relationships:['former lovers','estranged parents and children','old school friends','a mentor and their former pupil','two rivals writing anonymously','siblings living continents apart','a person and their younger self'],
  settings:['a summer villa overlooking the sea','a railway post office','a desk in an empty family home','a library preservation room','a ship nearing its final port','a mountain town after a storm','a city apartment during a blackout','a coastal hotel across three generations'],
  conflicts:['revealing the letter would bring closure to one person and harm another','someone can forgive the past but not its concealment','the addressee refuses to open the final message','a letter makes a promise no living person can fulfil','two versions of the same memory arrive in one envelope','a confession threatens an imminent celebration','the truth belongs to someone who never agreed to share it','the final reply can only be written after a public apology','there is one day left before the archive is sealed']
 },
 'Science & Discovery':{
  genres:['Hopeful science fiction','Scientific mystery','Climate fiction','Near-future speculative drama','First-contact tale','Medical ethics fiction','Space-station slice of life','Biopunk intrigue'],
  objects:['a sensor that records impossible weather','a botanical sample from an uncharted island','a telescope plate containing a second sun','a broken life-support gauge','a research notebook written in mirrored ink','a radio signal repeating a lullaby','a vial labelled with a tomorrow date','a map of vanished stars','a field recorder carrying a nonhuman voice'],
  twists:['the discovery is an invitation rather than a warning','the scientist is wrong for the right reasons','the test subject has been protecting the researchers','the experiment succeeds and nobody celebrates','the evidence suggests a new form of kindness','the alien message was meant for the laboratory cleaner','the missing variable is memory','the future proof is older than the present','the machine has been preserving a secret garden','the cure works but changes what counts as healthy','the discovery must remain unpublished to remain safe'],
  moods:['awe-struck','quietly philosophical','optimistic but fraught','suspenseful','lucid and melancholy','wonderfully strange','precise and tender'],
  characters:['a botanist on a final expedition','a station mechanic','a skeptical science journalist','an astronomer who fears the dark','a marine biologist','a lab technician seeking recognition','a linguist decoding first contact','a medic in a remote settlement'],
  relationships:['a researcher and their estranged sibling','two rival scientists','a mentor and a gifted apprentice','a station crew surviving an argument','a parent and a child born off-world','a field scientist and an island guide','a medic and a patient who refuses treatment'],
  settings:['a research vessel crossing warm ocean waters','a lunar greenhouse','a remote observatory in a storm','a climate-resilient island city','an underwater laboratory','a radio array on the edge of a desert','a medical outpost among glaciers','a university lab preparing for an ethics hearing'],
  conflicts:['an extraordinary discovery has ordinary ethical consequences','the research team must decide who may own the evidence','a discovery could save a community but alter its way of life','data integrity conflicts with friendship','the public needs an explanation the team cannot yet provide','a project can only survive by ending its original mission','a character must admit that curiosity caused harm','the only way to preserve the specimen is to set it free','the scientists disagree over whom their work is for']
 },
 'Satire & Mischief':{
  genres:['Absurdist social satire','Mythic workplace comedy','Royal-court farce','Comic mystery','Bureaucratic fantasy','Family holiday comedy','Speculative satire','Playful literary fiction'],
  objects:['a royal stamp that approves impossible requests','a complaint form with no final page','a crown delivered to the wrong address','a missing ceremonial teaspoon','a dragon’s employment contract','a magical queue ticket','a cake with the wrong inscription','a town noticeboard with prophetic typos','a parliamentary bell that refuses to ring'],
  twists:['the bureaucrat is the only person behaving reasonably','the prank accidentally improves public services','the impostor is elected unanimously','the rules require the villain to attend a picnic','the hero succeeds by refusing to be heroic','the royal decree is a shopping list','the suspected spy is simply very bad at introductions','the magical creature wants a union representative','the monster already completed every permit','the brilliant scheme is defeated by a neighbourhood auntie','everyone expects a scandal but gets a sincere apology'],
  moods:['deadpan','warmly ridiculous','sparkling and mischievous','satirical but humane','absurdly romantic','high-energy and chaotic','wickedly observant'],
  characters:['an overworked palace clerk','a chef mistaken for a diplomat','a dragon seeking paid leave','a very serious village mayor','a novice trickster','a gossip columnist who hates gossip','a book club president with a secret','an accidental royal'],
  relationships:['two rivals forced to co-chair a committee','a monarch and their exhausted assistant','siblings running a terrible business','a villain and their career coach','neighbours in a petty feud','a hero and their bewildered publicist','a trickster and an earnest detective'],
  settings:['a throne room during an inventory audit','a magical council budget meeting','a wedding rehearsal with the wrong couple','a chaotic neighbourhood street fair','a royal kitchen before a banquet','a library running a popularity contest','a town square full of competing proclamations','a diplomatic reception nobody planned'],
  conflicts:['the official plan is less sensible than the ridiculous alternative','an avoidable mistake becomes a national emergency','the community tries to solve a social problem with an ancient prophecy','the person with authority cannot get anyone to listen','everybody agrees on the goal but nobody agrees on the queue','someone must publicly admit their beautiful lie was a typo','a tiny insult triggers an extravagant contest','doing the honest thing violates a beloved tradition','the best solution would make the hero look foolish']
 },
 'Journeys & Expeditions':{
  genres:['Sea voyage adventure','Historical travel saga','Portal fantasy quest','Mountain survival','Archaeological mystery','Desert caravan tale','Space exploration','Railway odyssey'],
  objects:['a compass that points to unfinished business','a map with a missing island','a travel journal made from reused pages','a ticket for a train without a timetable','a brass sextant from a lost ship','a whistle heard only at night','an embroidered trail marker','a locked trunk carried for generations','a lantern whose flame leans toward home'],
  twists:['the destination is moving','the guide has never travelled this route before','the treasure is an unanswered question','the last traveller left a warning that reads like an apology','the safest route is through a forbidden place','the expedition is being followed by its own future','the journey was meant to bring two enemies together','the lost city wishes to remain lost','every milestone erases a part of the map','the first explorer is still waiting at the end','the travellers discover why previous groups turned back'],
  moods:['windswept','adventurous and lyrical','dangerous but hopeful','wistful and epic','strangely peaceful','intrepid','eerie and beautiful'],
  characters:['a hesitant ship navigator','an experienced caravan guide','a young cartographer','a botanist with a personal mission','a former soldier','a runaway noble','an engineer afraid of heights','an explorer who would rather stay home'],
  relationships:['two friends with different destinations','a guide and an arrogant sponsor','a mother and her adult child','rival mapmakers','a captain and a stowaway','an elder and a curious apprentice','former lovers stranded together'],
  settings:['a ferry crossing at dawn','a desert fort under new stars','a mountain pass before winter','an overgrown railway station','an ancient city beneath the waves','a ship crossing an unfamiliar current','a market where every road begins','a spacecraft nearing a dim blue planet'],
  conflicts:['turning back would protect the team but betray someone waiting','the map is accurate only when nobody believes it','a traveller must choose whom to trust with the last provisions','the expedition uncovers evidence of earlier injustice','the destination has changed since the promise was made','one companion is determined never to arrive','the route requires help from an enemy','the discovery cannot be brought home without destroying it','everyone must agree which story of the journey to tell']
 },
 'Poetry & Miniatures':{
  genres:['Lyrical microfiction','Narrative verse','Ekphrastic poem','Haiku-inspired scene','Prose poem','One-scene drama','Free-verse confession','Flash fable'],
  objects:['a raindrop on a sealed envelope','a blue feather on a doorstep','a cracked bowl full of light','a lost glove on a train','a wilted flower in a dictionary','a small bell beneath a pillow','a single candle in a tower','a salt-stained postcard','a teacup with a chip shaped like a moon'],
  twists:['the final image answers the first without repeating it','the speaker discovers a gentle contradiction','an ordinary sound becomes a turning point','one word means something different by the end','the described object belongs to the wrong person','the speaker is addressing an absence','the image is a memory rather than a place','the final line refuses to explain itself','a tiny gesture changes the stakes','a familiar image is made strange','a recurring colour acquires a second meaning'],
  moods:['tenderly spare','bright and wistful','restrained','melancholy but hopeful','dreamlike','jubilant','quietly devastating'],
  characters:['a person returning a key','a child counting clouds','someone waiting at a threshold','a musician after their last performance','a traveller watching dawn','a woman folding letters','a gardener hearing rain','a stranger who knows a name'],
  relationships:['a speaker and a lost friend','two people separated by a doorway','a parent remembering their child','a traveller and a place they are leaving','two people meeting after silence','a poet and their former self','a person writing to the sea'],
  settings:['the last five minutes before sunrise','a rain-streaked bus window','an empty concert hall','a garden after the guests have left','a beach at low tide','a kitchen with one light on','a station platform after departure','a rooftop during a meteor shower'],
  conflicts:['someone wants to speak but cannot find an honest sentence','a promise survives after its purpose has changed','leaving is both necessary and painful','the speaker must name an ordinary grief','a moment of happiness comes with a memory','an apology is attempted without an excuse','the poem must make silence perceptible','a goodbye becomes an invitation','a familiar place can no longer be entered']
 }
};
export const ORRERY_NEW_ORBIT_RECIPES=Object.entries(ORRERY_NEW_ORBITS).flatMap(([flavour,pool],familyIndex)=>
 Array.from({length:250},(_,index)=>{
  const j=index;
  return {
   id:'orrery-'+String(4013+familyIndex*250+j).padStart(4,'0'),
   flavour,
   genre:pool.genres[(j*5+familyIndex)%pool.genres.length],
   object:pool.objects[(j*7+familyIndex*3)%pool.objects.length],
   twist:pool.twists[(j*3+familyIndex*5)%pool.twists.length],
   mood:pool.moods[(j*5+familyIndex*2)%pool.moods.length],
   character:pool.characters[(j*3+familyIndex*4)%pool.characters.length],
   relationship:pool.relationships[(j*5+familyIndex*3)%pool.relationships.length],
   setting:pool.settings[(j*7+familyIndex*2)%pool.settings.length],
   conflict:pool.conflicts[(j*2+familyIndex*7)%pool.conflicts.length],
   difficulty:['Gentle','Standard','Challenging','Grand Challenge'][(j+familyIndex)%4]
  };
 }));
