import { useState } from 'react';
import badges from './badges.json';
import originals from './originalBadges.json';
import PalaceBadge from './PalaceBadge';
import './treasury.css';
const tiers=['bronze','silver','gold','platinum','emerald'];
export default function Treasury({Frame}) {
 const [collection,setCollection]=useState('originals');
 const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [tier,setTier]=useState('bronze');const [selected,setSelected]=useState(null);
 const source=collection==='originals'?originals:badges;
 const visible=source.filter(b=>(category==='all'||b.category===category)&&`${b.name} ${b.description} ${b.category}`.toLowerCase().includes(query.toLowerCase()));
 return <Frame privateArea><section className="room-title"><p className="eyebrow">COLLECT · ACHIEVE · CELEBRATE</p><h1>Royal Treasury</h1><p className="lede">The original 175 Palace badges, alongside the expanded achievement catalogue.</p><p>Explore the collection and its requirements. This catalogue shows requirements and art previews. Your verified progress and earned honours appear in the live Treasury.</p></section><div className="badge-collection-switch" role="group" aria-label="Badge collection"><button aria-pressed={collection==='originals'} onClick={()=>{setCollection('originals');setCategory('all');setSelected(null)}}>Palace originals · 175 badges</button><button aria-pressed={collection==='expanded'} onClick={()=>{setCollection('expanded');setCategory('all');setSelected(null)}}>Expanded paths · 100 families</button></div><div className="badge-controls"><label>Search badges<input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Name, category or goal"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(source.map(b=>b.category))].map(c=><option key={c}>{c}</option>)}</select></label><label>Preview tier<select value={tier} onChange={e=>setTier(e.target.value)}>{tiers.map(t=><option key={t} value={t}>{t[0].toUpperCase()+t.slice(1)}</option>)}</select></label></div><p role="status">{visible.length} badge families</p><div className="badge-grid">{visible.map(b=><article className="badge-card" key={b.id}><PalaceBadge family={b} tier={tier}/><small>{b.category} · {b.difficulty}</small><h2>{b.name}</h2><p>{b.description}</p><p className="badge-goal">{b.tiers.find(t=>t.slug===tier)?.threshold.toLocaleString()} · {b.unit||b.metric.replaceAll('_',' ')}</p><button onClick={()=>setSelected(selected===b.id?null:b.id)} aria-expanded={selected===b.id}>{selected===b.id?'Hide requirements':'View all tiers'}</button>{selected===b.id&&<ul className="badge-requirements">{b.tiers.map(t=><li key={t.slug}><strong>{t.name}</strong><span>{t.threshold.toLocaleString()}</span></li>)}</ul>}</article>)}</div>{!visible.length&&<p>No badges match these filters. Try another name or category.</p>}</Frame>;
}

